### ISSUE TITLE
Find rdm and rc executables in elpa folder

### ISSUE THREAD

**Issue by ghost** [atilaneves/cmake-ide#100]
I am using `rtags-install` in emacs to install rtags.
Since this installs rtags into a directory in `.emacs.d/elpa/...`, cmake-ide is not able to start the rdm server.
Is there a way to make cmake-ide search for these executables in my `.emacs.d/elpa` folder?

**Comment by atilaneves** [comment]
Yes, add that directory to your `PATH`

**Comment by s-kostyaev** [comment]
@atilaneves I think the better solution is use `rtags-executable-find` inside `cmake-ide` code. I can do PR if you want.

**Comment by atilaneves** [comment]
@s-kostyaev Yes, please submit a PR.

**Comment by s-kostyaev** [comment]
@atilaneves done
