### ISSUE TITLE
Automatic recompilation not triggered after file saved

### ISSUE THREAD

**Issue by novakboskov** [atilaneves/cmake-ide#103]
I'm trying `cmake-ide` with a simple hello world project and have an issue either with understanding what `cmake-ide` does or its configuration.

When I explicitly call `M-x cmake-ide-compile` everything is compiled correctly but it is not triggered automatically when I change something and save the file.

Configuration of `cmake-ide` itself is pretty simple like `(cmake-ide-setup)` but what to do when it doesn't work as expected?

**Comment by atilaneves** [comment]
`cmake-ide-setup` doesn't ask emacs to recompile on save. You'd have to [configure that yourself](https://www.gnu.org/software/emacs/manual/html_node/elisp/Standard-Hooks.html).

**Comment by novakboskov** [comment]
OK, thanks.
