### ISSUE TITLE
Add ability to use cmake-server mode

### ISSUE THREAD

**Issue by myrgy** [atilaneves/cmake-ide#109]
Hello, seems that this feature will allow to perform deferred project parsing:
https://cmake.org/cmake/help/v3.7/manual/cmake-server.7.html

**Comment by atilaneves** [comment]
That'd be pretty cool, but probably a lot of work. It's unlikely I'm going to look into this.

**Comment by myrgy** [comment]
will add comment to https://github.com/atilaneves/cmake-ide/issues/47
