### ISSUE TITLE
ac-c-header support

### ISSUE THREAD

**Issue by espositofulvio** [atilaneves/cmake-ide#11]
At the moment I've got the following advice in my init.el but would be greate to add a one line to set achead:include-directories as well in cmake-ide:

```elisp
(defun set-ac-c-header-path (buffer flags includes sys-includes)
  (when (buffer-live-p buffer)
    (with-current-buffer buffer
      (make-local-variable 'achead:include-directories)
      (setq achead:include-directories (append achead:include-directories (cmake-ide--flags-to-include-paths flags)))
    )))

(advice-add 'cmake-ide-set-compiler-flags :after #'set-ac-c-header-path)
```

**Comment by atilaneves** [comment]
I wouldn't depend on `cmake-ide--flags-to-include-paths`, as the double hyphen indicates it's a private variable. I see what you mean with this issue, but I don't really think it's the job of `cmake-ide`. Here's what I do in my `init.el`:

    ; autocomplete headers
    (add-hook 'c++-mode-hook (lambda()
                               (require 'auto-complete-c-headers)
                               (setq ac-sources '(ac-source-clang ac-source-words-in-same-mode-buffers))
                               (add-to-list 'ac-sources 'ac-source-c-headers)
                               (setq achead:include-directories
                                     (append achead:include-directories (c++-include-paths)))))

    (defun gcc--include-paths-from-output (output)
      "Find the g++ include paths in OUTPUT.
    The output lines contains the include paths between the following lines:
    #include <...> search starts here:
    ...
    End of search list"
      (let* ((lines (split-string output "\n"))
             ;; start-includes slices off everything before the section we're interested in
             (start-includes (cdr (member "#include <...> search starts here:" lines)))
             ;; The list of include paths is found by reversing the list, searching for the end,
             ;; leaving out (cdr) the string we search for, and reversing it back
             (includes (reverse (cdr (member "End of search list." (reverse start-includes))))))
        ; strip out whitespace
        (mapcar (lambda (x) (replace-regexp-in-string " " "" x)) includes)))


    (defun c++-include-paths ()
      "Find the g++ include paths and return a list of strings."
      (gcc--include-paths-from-output (shell-command-to-string "gcc -v -xc++ /dev/null -fsyntax-only")))
