### ISSUE TITLE
Converting JSON CDB ... to IDB; split-string: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by piojanu** [atilaneves/cmake-ide#113]
Hi!

I encountered a problem using cmake-ide and bear. Here I have my example project where it reproduces: https://github.com/piojanu/example-cmake-ide.
I got variables in .dir-locals.el pointing to my home directory. You will have to change this.
Then run `bear make` in project root dir, to produce compile_commands.json.

When I open emacs with configured rtags and cmake-ide I get this:
```
cmake-ide [Fri Jun 16 10:56:21 2017]: Converting JSON CDB /home/pjanusze/Documents/cmake-ide-sample/compile_commands.json to IDB
split-string: Wrong type argument: stringp, nil
```

Could you help me?
Thanks,
Piotr

**Comment by piojanu** [comment]
I made such an experiment:
I written CMakeLists.txt and generated compile commands from it (and makefile). It worked.
Then I deleted it and tried `bear makefile` to generate compile commands. I got error from above.

**Comment by piojanu** [comment]
Worth noting that irony works fine with this compile_commands.json.

**Comment by atilaneves** [comment]
I haven't had time to look at this but I guess it's because bear doesn't seem to generate a `command` entry.

**Comment by piojanu** [comment]
After your hint I found this: https://github.com/Andersbakken/rtags/issues/955
Strange, because I use fresh clang 3.9.1, so it should work. I guess it's not cmake-ide related (as long as it doesn't use own old clang ;) ). If you agree, you can close this issue.

Thanks,
Piotr

**Comment by atilaneves** [comment]
According to [this](https://clang.llvm.org/docs/JSONCompilationDatabase.html) either of `command` or `arguments` must be present. This is news to me - and yes, it's a cmake-ide issue since it should work with either.

**Comment by piojanu** [comment]
Now my emacs doesn't start. It just freezes and in minibuffer there is "cmake-ide: Running rc for rtags", or something like this. --debug-init doesn't catch anything. It can be, that my project is that big, that it's processing it so long? Manually everything works fine (when I run rc -J manually). Some help, how can I debug it?

**Comment by atilaneves** [comment]
You could look at the rdm buffer to see if it says anything there. I can't reproduce this, and can't see how the last change would break cmake-ide

**Comment by piojanu** [comment]
Yea, I also can't reproduce it on smaller project. In big one it just freezes and I can't do anything. For now I use rtags mechanism for running rdm:
```
(add-hook 'c-mode-hook 'rtags-start-process-unless-running)
(add-hook 'c++-mode-hook 'rtags-start-process-unless-running)
```
and I rely on irony-mode automagically finding my compile_commands.json.

Could you explain what are cmake-ide-project-dir and cmake-ide-build-dir variables responsible for and how should I set them? It isn't well explained in README.md. I just set them to where my compile_command.json is (which is also root of my project).

**Comment by atilaneves** [comment]
`cmake-ide-project-dir` is where the project is, i.e. the root dir of the source code. `cmake-ide-build-dir` is where the build happens, i.e. where `compile_commands.json` is.

If this is only a problem in a big project it's probably a performance issue, in which case it makes sense that it started after the fix for this issue given how I fixed it. I'll see what I can do.
