### ISSUE TITLE
Accompanying files are not installed

### ISSUE THREAD

**Issue by egarrulo** [atilaneves/cmake-ide#12]
After installing CMake IDE by means of the package manager, the README, TODO and LICENSE are not present in the package directory.

Thanks for your attention and for sharing this useful package.

**Comment by atilaneves** [comment]
Should they be?

**Comment by egarrulo** [comment]
If they do, they will always be aligned with the installed version.

**Comment by egarrulo** [comment]
Sorry, I didn't consider that adding more files to a package installable via Elpa may be a complex procedure.  If this is the case, please ignore this request.
