### ISSUE TITLE
cmake-ide-build-dir is ignored

### ISSUE THREAD

**Issue by ddanilov** [atilaneves/cmake-ide#122]
Some recent changes have broken the `cmake-ide-build-dir` behaviour. When I set the variable e.g. in `*scratch*` buffer by `(setq cmake-ide-build-dir "/home/denis/project/build")` and then open a cpp-file, my setting is ignored and cmake runs in a temporary build directory under `/tmp/...`

PS: An older version corresponding to 0d05b0 works fine and still respects the `cmake-ide-build-dir` value

**Comment by earthfront** [comment]
+1

**Comment by atilaneves** [comment]
I just merged a PR that I think fixes it. Should be available on MELPA today.

**Comment by ddanilov** [comment]
thanks, the new version from melpa worked in my case

**Comment by atilaneves** [comment]
Good, I'll close it then. Sorry for the disturbance.
