### ISSUE TITLE
cmake-ide looks for compilation DB in the wrong directory

### ISSUE THREAD

**Issue by zaript** [atilaneves/cmake-ide#125]
I am attempting to use cmake-ide in macosx and getting the error listed below:

`cmake-ide [Mon Jul 31 19:34:43 2017]: Starting rdm server
cmake-ide [Mon Jul 31 19:34:43 2017]: Running cmake for src path ~/local/sandbox/cpp/ in build path /var/folders/9_/pjdjxmkn6_59qw9hy0tq8t400000gn/T/cmake74552-4q/
cmake-ide [Mon Jul 31 19:34:46 2017]: Finished running CMake
cmake-ide [Mon Jul 31 19:34:46 2017]: Non-existent compilation DB file /var/folders/9_/pjdjxmkn6_59qw9hy0tq8t400000gn/T/cmake74552lex/compile_commands.json
error in process sentinel: cmake-ide--idb-file-to-obj: Wrong type argument: hash-table-p, nil
`

In the cmake buffer things seem to go well:

`-- Build files have been written to: /var/folders/9_/pjdjxmkn6_59qw9hy0tq8t400000gn/T/cmake74552-4q
`

It seems, that cmake-ide looks for the compilation DB in the wrong directory.

**Comment by novakboskov** [comment]
Same issue here.

**Comment by atilaneves** [comment]
I don't have a mac, so I can't reproduce this myself.

**Comment by novakboskov** [comment]
I have the same issue on Linux only difference is that `*cmake*` buffer reports:
```
-- Build files have been written to: 
/home/me
```
and that it looking for compilation file in the source directory.
It started happening after last merge #124 . Previously it used `/tmp` to store build files.

**Comment by atilaneves** [comment]
@novakboskov Thanks for the diagnosis. I'll look into this.
