### ISSUE TITLE
Setting current directory: No such file or directory, build/

### ISSUE THREAD

**Issue by hicksy994** [atilaneves/cmake-ide#126]
Hi, after I guess a recent update I get this error when opening a project. I am setting the build dir with

        (setq cmake-ide-build-dir "build/"))

If I don't set it it uses the temp directory and everything works fine.

**Comment by hicksy994** [comment]
I never had to do this before, did this change with a new version? In that case can you now not set it generally for any project? (i.e. use a build directory in the root of each project)

**Comment by atilaneves** [comment]
There were a few changes merged in by a user and I think that might have changed it. You can set it per-project as usual, just use the absolute path. For now, anyway, I might work on making this better.

**Comment by atilaneves** [comment]
Closed by #138

**Comment by hvkwak** [comment]
I am new to Emacs. Is there a way to use a ```build``` directory in the root of each project and keep ```cmake-ide-build-dir``` relative? What shall I change in ```init.el```? I think I missed something. I hope I don't have to have ```.dir-locals.el``` in the root of each project. One line of example for a piece of information below from README may be a great help for newbies.

> By using both cmake-ide-build-pool-dir and cmake-ide-build-pool-use-persistent-naming, you can fully do away with the need to configure a build directory per project with directory local variables (for example).

**Comment by hvkwak** [comment]
> I am new to Emacs. Is there a way to use a `build` directory in the root of each project and keep `cmake-ide-build-dir` relative? What shall I change in `init.el`? I think I missed something. I hope I don't have to have `.dir-locals.el` in the root of each project. One line of example for a piece of information below from README may be a great help for newbies.
> 
> > By using both cmake-ide-build-pool-dir and cmake-ide-build-pool-use-persistent-naming, you can fully do away with the need to configure a build directory per project with directory local variables (for example).

I somehow managed to do this! Thanks to https://github.com/dfrib/emacs_setup/blob/master/.emacs.d/init.el !
```
(use-package cmake-ide
  :after rtags
  :config
  ;; set path to project build directory
  (setq cmake-ide-build-pool-use-persistent-naming t)
  (setq cmake-ide-build-pool-dir default-directory)
  (setq cmake-ide-build-dir "build")
  ;; invoke cmake-ide setup
  (cmake-ide-setup)
  )
```
This will do the job. I tested that it works without ```(setq cmake-ide-build-pool-dir default-directory)```, too. I hope it helps newcomers.
