### ISSUE TITLE
Wrong argument error stringp 45 whenever i open a cpp file

### ISSUE THREAD

**Issue by Sean-Nerq** [atilaneves/cmake-ide#129]
Sorry for the unwieldy backtrace below

Debugger entered--Lisp error: (wrong-type-argument stringp 45)
  string-match("^-m32$" 45)
  #[257 "\300\301\302:\203!@\262\303\304\305\"\"?\211\262\203!A\262\202\211\205&\302\207" [("-m32" "-Werror" "-c" "-fPIC" "-pipe" "-g" "-ggdb") nil t string-match format "^%s$"] 8 "\n\n(fn X)"](45)
  #[257 "\300!\205\211\207" [#[257 "\300\301\302:\203!@\262\303\304\305\"\"?\211\262\203!A\262\202\211\205&\302\207" [("-m32" "-Werror" "-c" "-fPIC" "-pipe" "-g" "-ggdb") nil t string-match format "^%s$"] 8 "\n\n(fn X)"]] 3 "\n\n(fn X)"](45)
  mapcar(#[257 "\300!\205\211\207" [#[257 "\300\301\302:\203!@\262\303\304\305\"\"?\211\262\203!A\262\202\211\205&\302\207" [("-m32" "-Werror" "-c" "-fPIC" "-pipe" "-g" "-ggdb") nil t string-match format "^%s$"] 8 "\n\n(fn X)"]] 3 "\n\n(fn X)"] (45 73 47 117 115 114 47 105 110 99 108 117 100 101 47 99 43 43 47 118 49 47 55 46 49 46 49 47 "-O3" "-DNDEBUG" "-o" "CMakeFiles/Hello.dir/hello.cpp.o" "-c"))
  cmake-ide--filter(#[257 "\300\301\302:\203!@\262\303\304\305\"\"?\211\262\203!A\262\202\211\205&\302\207" [("-m32" "-Werror" "-c" "-fPIC" "-pipe" "-g" "-ggdb") nil t string-match format "^%s$"] 8 "\n\n(fn X)"] (45 73 47 117 115 114 47 105 110 99 108 117 100 101 47 99 43 43 47 118 49 47 55 46 49 46 49 47 "-O3" "-DNDEBUG" "-o" "CMakeFiles/Hello.dir/hello.cpp.o" "-c"))
  cmake-ide--filter-ac-flags((45 73 47 117 115 114 47 105 110 99 108 117 100 101 47 99 43 43 47 118 49 47 55 46 49 46 49 47 "-O3" "-DNDEBUG" "-o" "CMakeFiles/Hello.dir/hello.cpp.o" "-c"))
  cmake-ide-set-compiler-flags(#<buffer hello.cpp> ("-O3" "-DNDEBUG" "-o" "CMakeFiles/Hello.dir/hello.cpp.o" "-c") nil nil)
  cmake-ide--set-flags-for-src-file(((directory . "/home/nerq/Projects/Hello_World") (command . "/usr/bin/c++    -O3 -DNDEBUG   -o CMakeFiles/Hello.dir/hello.cpp.o -c /home/nerq/Projects/Hello_World/hello.cpp") (file . "/home/nerq/Projects/Hello_World/hello.cpp")) #<buffer hello.cpp> nil)
  cmake-ide--set-flags-for-file(#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("/home/nerq/Projects/Hello_World/hello.cpp" (((directory . "/home/nerq/Projects/Hello_World") (command . "/usr/bin/c++    -O3 -DNDEBUG   -o CMakeFiles/Hello.dir/hello.cpp.o -c /home/nerq/Projects/Hello_World/hello.cpp") (file . "/home/nerq/Projects/Hello_World/hello.cpp"))) ...)) #<buffer hello.cpp>)
  #[257 "\301\300\"\207" [#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("/home/nerq/Projects/Hello_World/hello.cpp" (((directory . "/home/nerq/Projects/Hello_World") (command . "/usr/bin/c++    -O3 -DNDEBUG   -o CMakeFiles/Hello.dir/hello.cpp.o -c /home/nerq/Projects/Hello_World/hello.cpp") (file . "/home/nerq/Projects/Hello_World/hello.cpp"))) ...)) cmake-ide--set-flags-for-file] 4 "\n\n(fn X)"](#<buffer hello.cpp>)
  mapc(#[257 "\301\300\"\207" [#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("/home/nerq/Projects/Hello_World/hello.cpp" (((directory . "/home/nerq/Projects/Hello_World") (command . "/usr/bin/c++    -O3 -DNDEBUG   -o CMakeFiles/Hello.dir/hello.cpp.o -c /home/nerq/Projects/Hello_World/hello.cpp") (file . "/home/nerq/Projects/Hello_World/hello.cpp"))) ...)) cmake-ide--set-flags-for-file] 4 "\n\n(fn X)"] (#<buffer hello.cpp>))
  cmake-ide--on-cmake-finished()
  cmake-ide-maybe-run-cmake()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer hello.cpp> "~/Projects/Hello_World/hello.cpp" nil nil "~/Projects/Hello_World/hello.cpp" (4983042 2057))
  find-file-noselect("~/Projects/Hello_World/hello.cpp" nil nil t)
  find-file("~/Projects/Hello_World/hello.cpp" t)
  funcall-interactively(find-file "~/Projects/Hello_World/hello.cpp" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)

**Comment by atilaneves** [comment]
Can you point me to a reduced project that reproduces this issue? Thanks.

**Comment by Sean-Nerq** [comment]
I'm not getting you but if u mean a simple project... this is a hello world project with an in build

**Comment by atilaneves** [comment]
I can't reproduce this, I just opened a C++ file with the latest version of cmake-ide.

**Comment by Sean-Nerq** [comment]
sorry... then it must be my bad configurations... i'll uninstall cmake-ide and the other tools and reconfigure to see if i'll get the same error

**Comment by gavrushkin** [comment]
I have the same issue, I think it is caused by some layer conflict.

@Sean-Nerq, please reply if you find solution.

**Comment by atilaneves** [comment]
@gavrushkin If you can provide a test project that reproduces this I can look into it.

**Comment by gavrushkin** [comment]
@atilaneves I can't do it, sorry. It is a closed-source project.

**Comment by atilaneves** [comment]
@gavrushkin I see. In that case there's not much I can do - you'd have to debug it yourself.

**Comment by gavrushkin** [comment]
@atilaneves  I commented cmake--ide-filter function body and it works now. Sorry, I'm new to lisp/emacs so I don't get into it deep.

**Comment by finjulhich** [comment]
@atilaneves 
I'm getting this as well.
rdm/rc compiled myself according to github
rtags 20180130.942 emacs package installed
cmake-ide 20180205.903 emacs package installed

Here are a snippet of Messages ( ~/.emacs loads everything )

cmake-ide [Sat Feb 10 16:36:08 2018]: Starting rdm server
cmake-ide [Sat Feb 10 16:36:09 2018]: Converting JSON CDB <homedir>/blitzq-build-release/compile_commands.json to IDB
cmake-ide [Sat Feb 10 16:36:09 2018]: Setting flags for file <homedir>/blitzq/callables/backtest_strategy.hpp
Working...
Finding buffer src1.cpp...
Finding ./src1.cpp...
./src1.cpp found
cmake-ide [Sat Feb 10 16:36:09 2018]: Found src file ...cpp for ....hpp, using its flags
Wrong type argument: stringp, 45

How do I turn on debug to get more Messages to see what's going?

**Comment by atilaneves** [comment]
@finjulhich Any chance I could get access to that `compile_commands.json`?

**Comment by gavrushkin** [comment]
@finjulhich 
This issue was fixed for me after I updated all emacs packages to the latest version. Later it appeared again in a quite random way.

**Comment by ultronozm** [comment]
I encountered this error just now with the most recent version, even with a "hello" project:

`hello-cpp/CMakeLists.txt`:

```
cmake_minimum_required(VERSION 3.10)
project(hello-cpp)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS "-g")
add_executable(hello hello.cpp)
```

`(find-file "hello.cpp")` gives the same error as the previous commenters.

After a bit of debugging, it seems that the variable `cmake-ide-flags-c++` is documented as a string (and I set it as such in my init file), but is treated by `cide--get-compiler-flags` as if it were a list of strings.  The latter function reads:

```
(defun cide--get-compiler-flags (flags)
  "Use FLAGS to return all compiler flags including existing ones."
  (append (cide--get-existing-compiler-flags) flags))
```

Modifying it as follows seems to fix the issue:

```
(defun cide--get-compiler-flags (flags)
  "Use FLAGS to return all compiler flags including existing ones."
  (append (split-string (cide--get-existing-compiler-flags)) flags))
```
