### ISSUE TITLE
flycheck complains about C++11 feature when set(CMAKE_CXX_FLAGS "-std=c++11")

### ISSUE THREAD

**Issue by sizur** [atilaneves/cmake-ide#13]
Should cmake-ide-clang-flags-c or cmake-ide-flags-c++ be set even though CMakeLists.txt has set(CMAKE_CXX_FLAGS "-std=c++11")?

Should this not be picked up from compile_commands.json's "command": "/usr/bin/c++    -std=c++11 ... ?

Or is my config wrong?

flycheck and rtags are loaded before the cmake-ide.

**Comment by sizur** [comment]
In other words,

flycheck-gcc-language-standard and flycheck-clang-language-standard are not set accordingly.

**Comment by atilaneves** [comment]
Only just noticed this myself the other day, thanks for filing the bug. Basically flycheck updated itself with new variables and cmake-ide hasn't caught up yet. I'll fix this.

**Comment by atilaneves** [comment]
Easiest thing for now is to set the flycheck variable yourself, but I'll see to this.

**Comment by atilaneves** [comment]
So I think this is a flycheck configuration issue. I've changed my config to set `flycheck-clang-language-standard` and all is fine.

**Comment by sizur** [comment]
Should this not be set automatically per project?

**Comment by atilaneves** [comment]
It could... but not easily. `cmake-ide` would have to recognise `-std=...` options for each file and then set it. It's doable but POSIX-dependent and a bit fragile.
