### ISSUE TITLE
/usr/include directory does not exist in Mac OS

### ISSUE THREAD

**Issue by xinquanatcolezhu** [atilaneves/cmake-ide#130]
Hi 

This is a great tool and I know it from your cpp-con youtube video. It works great on Linux but I am having a problem in my Mac OS X system which does not have /usr/include/ directory

cmake-ide [Sun Sep 17 18:20:34 2017]: Making directory /var/folders/nl/gf1zldh16xb32t9tpbhxpbp40000gn/T/cmake7802vKu
File mode specification error: (user-error Looking for `(repeat (directory :tag "Include directory"))' in `("/usr/include/")' failed because:
Looking for `(directory :tag "Include directory")' in `"/usr/include/"' failed because:
  directory is not accessible)

**Comment by atilaneves** [comment]
`/usr/include` isn't hard-coded anywhere in `cmake-ide`. Is it possible that your `compile_commands.json` mentions it?

**Comment by xinquanatcolezhu** [comment]
thanks for the quick reply. I will check my cmake file again. !!! thank very much!!!
