### ISSUE TITLE
doesn't work in clang 5.0

### ISSUE THREAD

**Issue by amosbird** [atilaneves/cmake-ide#132]
I got
```
cmake-ide [Thu Sep 28 12:20:45 2017]: Setting flags for file /home/amos/git/ClickHouse/dbms/src/Interpreters/Compiler.cpp
Suspicious state from syntax checker c/c++-clang: Flycheck checker c/c++-clang returned non-zero exit code 1, but its output contained no errors: clang-5.0: error: argument unused during compilation: '-nopie'

Try installing a more recent version of c/c++-clang, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by atilaneves** [comment]
I have clang 5.0.0 and it works fine. From your error message it seems clang doesn't know or didn't know what `-nopie` is and I guess you're compiling with `-Werror`. In any case, this has nothing to do with the clang version (unless `-nopie` was changed). Use `flycheck-compile` to get the output from flycheck running clang. If there's a bug with cmake-ide that you see then, open a new issue.
