### ISSUE TITLE
add cmake-ide-run-project?

### ISSUE THREAD

**Issue by Red-Portal** [atilaneves/cmake-ide#136]
```cmake-ide-compile```
is great but could we also add ```cmake-ide-run-project```?
currently I have to go to the temp cmake-ide path or build the project on the shell and then run the binaries.

If cmake-ide does not have enough information enough to do that,
I think recursively finding all binary types from root and then listing them in a buffer would do the trick.

**Comment by atilaneves** [comment]
What I do is to set the compilation command to also run the binary (usually the unit tests), e.g.

```elisp
(setq cmake-ide-compile-command "ninja -C $BUILD_DIR && $BUILD_DIR/myapp")
```
Also, the temporary build path is there for convenience, I wouldn't recommend using it regularly. Instead, set a dir-local `cmake-ide-build-dir` per project. `cmake-ide-compile-command` can (should?) also be set as dir-local per project.

**Comment by Red-Portal** [comment]
It would be great to have a way to do that automatically.

And about the build path, I think adding that recommendation to the README would be great
