### ISSUE TITLE
‘levenshtein-0’ is unavailable

### ISSUE THREAD

**Issue by LingxiangYu** [atilaneves/cmake-ide#137]
Hi Atila,
I'm trying to install cmak-ide. However, the "‘levenshtein-0’ is unavailable" problem drives me crazy! I looked into some closed issues here and tried to download levenshtein.el by myself. I used "M-x byte-comile-file" to install levenshtein. Unfortunately, when I used M-x package-install RET cmake-ide, I still got "‘levenshtein-0’ is unavailable". Please help me to take look at the issue. 
Thank you very much in advance.

**Comment by atilaneves** [comment]
I remember the closed issues, but my problem is I was never able to reproduce it, so I can't fix it. What version of Emacs are you using?

**Comment by LingxiangYu** [comment]
I'm using Emacs 25.1.1. I'm thinking about one way to go around the problem. Is it possible that I just copy all your code 'cmake-ide.el' into my 'emacs.el'? 
Thanks a lot.

**Comment by atilaneves** [comment]
You could... but I wouldn't recommend it. You'd still be missing levenshtein anyway. I'm wondering if the 0 version is the issue? When you installed levenshtein you should have gotten a directory with its files in `.emacs.d/elpa`. That should have a version string inside. What is it?

**Comment by LingxiangYu** [comment]
Thanks a lot for fast response. Actually, since I read that previous closed issue and tried to downloaded levenshtein.el by myself, I named that file as levenshtein-0.el and then compiled it. So, right now, in my elap folder, there is levenshtein.elc file.

**Comment by atilaneves** [comment]
Renaming it shouldn't really work - the version is handled differently. If you have `levenshstein.elc` then supposedly `(require 'levenshtein)` works, no?

**Comment by LingxiangYu** [comment]
Yes!! You're right. I changed "levenshstein-0.el" back to "levenshstein.el" and then re-compiled it. So, I have "levenshstein.elc" in elpa folder. Now, I finally could install cmake-ide. Thanks a lot!

**Comment by Peter-JanGootzen** [comment]
I also ran into this issue, the problem was that I was using the stable MELPA repository. You need to use the unstable repository at https://melpa.org/packages/.
