### ISSUE TITLE
Project dir not properly set

### ISSUE THREAD

**Issue by emacsuser123** [atilaneves/cmake-ide#140]
Hello.

I'm having problems trying to run cmake from cmake-ide package in emacs.

I have the typical cmake structure, where a _build_ dir exists to generate out-of-place compilations there, not involving any source file directory. In fact, _src_ directory is at the same level, both _src_ and _build_ are children of the project top directory. The CMakeLists.txt file is placed under the project top level directory.

Typically, I _cd_ into the build directory and run _cmake .._  there without any problem, using the command line. All files are generated under build, without interfering the rest of the stuff.

But if I run it inside emacs with cmake-ide, the files are generated under the project top directory.

Taking a look at the .el code of cmake-ide package, I think there is a problem on the cmake-ide-run-cmake function, where it says:

   ```
 (let ((project-dir (cmake-ide--locate-cmakelists)))
      (when project-dir ; no point if it's not a CMake project
        ;; register this buffer to be either a header or source file
        ;; waiting for results
        (cmake-ide--add-file-to-buffer-list)
        (let ((cmake-dir (cmake-ide--get-build-dir)))
          (let ((default-directory cmake-dir))
            (cmake-ide--run-cmake-impl project-dir cmake-dir)
            (cmake-ide--register-callback)))))))
```
So, project-dir is being assigned an entire path, including the _CMakeLists.txt_ filename.
(Please note that I have _cmake-ide-cmakelists-dir_ variable set to the project top directory, where the _CMakeLists.txt_ file lives).
If I run cmake under the build dir with the entire string as a parameter, including the filename, files are generated on the project top directory, and not in the current build directory.

I think that assignment should use the dirname (excluding filename) of the _CMakeLists.txt_.

Thanks and regards.
-Bob V

**Comment by dlyr** [comment]
Hi, it's funny i'm also on the same thing. 
as far as I know, `cmake-ide--locate-cmakelists` return the directory I think.
If you want to specify your build dir, simply set `cmake-ide-build-dir`. If not set, `cmake-ide-run-cmake` will create the build dir for you.

As I understand, project-dir is the _same_ as cmakelists-dir, except if you have multiple project with a parent CMakeLists.txt that you don't want to use.

I have tried to modifiy project-dir and change every call to `cmake-ide--locate-cmakelists`  to `cmake-ide--locate-project-dir` but it is under tests for now.

**Comment by atilaneves** [comment]
The only I can think of (barring bugs) of the CMake files being generated in the project dir is if `cmake-ide-build-dir` is set to that directory. By default cmake-ide generates a temporary directory to build the project in. Since that would mean building from scratch every time you reboot, the recommended way is to set `cmake-ide-build-dir` via a directory-local variable, that way the build always happens in the same directory. In your case that would be `build`.

`cmake-ide--locate-cmakelists` returns a directory.

**Comment by emacsuser123** [comment]
I am not an expert on emacs lisp at all, to be honest, but the function implementation is as follows:

```
(defun cmake-ide--locate-cmakelists ()
  "Find the topmost CMakeLists.txt file."
  (if cmake-ide-cmakelists-dir
      (expand-file-name "CMakeLists.txt" cmake-ide-cmakelists-dir)
    (cmake-ide--locate-cmakelists-impl default-directory nil)))
```

I think that the whole path of _CMakeLists.txt_ file (including the filename) will be returned whenever _cmake-ide-cmakelists-dir_ is set. That is how expand-file-name behaves.

Regards.
-Bob V

**Comment by atilaneves** [comment]
@emacsuser123 I opened a project and ran `cmake-ide--locate-cmakelists`. It returned the directory. Nothing like _running_ the code to know what it does ;)

Try it yourself: `M-: (cmake-ide--locate-cmakelists)`

**Comment by emacsuser123** [comment]
Sorry, but I think you have not read my statement carefully enough.
Of course that function may return a directory. But, as I said, if _cmake-ide-cmakelists-dir_ is not nil, it will return the _expand-file-name_  result, which in turn will be a whole path, including the filename.
As you said, nothing like running the code itself to know what it does, and that is precisely what I did:
_(expand-file-name "CMakeLists.txt" "/path/to/CMakeLists.txt/file")_, and it returned a file path:
_"/path/to/CMakeLists.txt/file/CMakeLists.txt"_

**Comment by atilaneves** [comment]
Ah, ok, sorry for the misunderstanding. I set both `cmake-ide-cmakelists-dir` (normally not needed) and `cmake-ide-build-dir` and managed to reproduce this.
