### ISSUE TITLE
Hyphen ( - ) in file path breaks setting for flycheck-clang-args

### ISSUE THREAD

**Issue by anuragm** [atilaneves/cmake-ide#142]
Since we are parsing flycheck clang arguments by checking for a hyphen symbol, a hyphen in the filename breaks proper setting for `flycheck-clang-args` which in turn breaks other flags.

There is a minimal working example in the attached [sample.zip](https://github.com/atilaneves/cmake-ide/files/1540755/sample.zip). For example,

```
cd ~
mkdir "name - with hyphen"
cd "name - with hyphen"
touch main.cpp
touch CMakeLists.txt
```
Contents of `main.cpp`
```
#include <cstdio>

int main(){
  std::printf("Hello World!\n");
  return 0;
}
```
Contents of `CMakeLists.txt`
```
cmake_minimum_required (VERSION 2.6)
set(CMAKE_CXX_EXTENSIONS OFF)
add_definitions(-Wall -Wextra -pedantic)
project (Hello)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(SOURCE main.cpp)
add_executable (hello ${SOURCE})
set_property(TARGET hello PROPERTY CXX_STANDARD 14)
```

Opening the file in Emacs leads to this error message,
```
cmake-ide [Thu Dec  7 13:53:18 2017]: Setting flags for file /Users/anon/name - with hyphen/main.cpp
Suspicious state from syntax checker c/c++-clang: Flycheck checker c/c++-clang returned non-zero exit code 1, but its output contained no errors: clang: error: no such file or directory: '"/Users/anon/name'
clang: error: -E or -x required when input is from standard input
clang: error: no such file or directory: 'with'
clang: error: no such file or directory: 'hyphen/main.cpp"'

Try installing a more recent version of c/c++-clang, and please open a bug report if the issue persists in the latest 
```
This happens because `cmake-ide` sets `flycheck-clang-args` to `("-O3" "-Wall" "-Wextra" "-pedantic" "-o" "CMakeFiles/hello.dir/main.cpp.o" "-c" "\"/Users/anon/name" "-" "with" "hyphen/main.cpp\"")`

**Comment by anuragm** [comment]
I think an obvious workaround is `Don't name your folders with an hyphen!!111`. But I am stuck with these folder names for now.

**Comment by atilaneves** [comment]
The hyphen isn't even the main problem - it's having a space in there that is. This is a lot more difficult to fix than I thought as well.

**Comment by anuragm** [comment]
@atilaneves The fix is working! Thanks! But there is one small problem. Using `subseq` requires common lisp. I don't have any other package loading `cl`, so I have to manually require it before I load `cmake-ide`. Perhaps we can have `cmake-ide` require `cl` package as well.

The error I am getting in the Messages window is

`error in process sentinel: cmake-ide--unquote: Symbol’s function definition is void: subseq`

**Comment by windtail** [comment]
{
        "command": "cc -c -Wp,-MD,tools/.fit_image.o.d -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer -include ./include/libfdt_env.h -idirafterinclude -idirafter./arch/arm/include -I./lib/libfdt -I./tools -DUSE_HOSTCC -D__KERNEL_STRICT_NAMES -D_GNU_SOURCE -DMKIMAGE_DTC=\\\"dtc\\\" -o tools/fit_image.o tools/fit_image.c",
        "directory": "/home/ljj/dev/u-boot",
        "file": "/home/ljj/dev/u-boot/tools/fit_image.c"
    },

extracted from [u-boot](http://www.denx.de/wiki/U-Boot/) compile_commands.json generated by bear

split-string-and-unquote  failed with **End of file during parsing**

**Comment by atilaneves** [comment]
@windtail I can reproduce that.

**Comment by windtail** [comment]
simple split-string will do, cause the diversity of compile commands, should we add an option for custom splitting function and by default only consider simple cases without hypen and whitespace in file path

**Comment by windtail** [comment]
i mean, in my special situation, at lease no error generated :)
