### ISSUE TITLE
error when opening c Makefile project 

### ISSUE THREAD

**Issue by myrgy** [atilaneves/cmake-ide#145]
From here: https://github.com/syl20bnr/spacemacs/issues/9985

Upon launching a c makefile project, an error pops up in the bottom message buffer

Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/media/aj/Buffer/git-clones/myobeam/jag-freertos-revA/src/main.c" nil)
  cmake-ide--idb-file-to-obj(nil "/media/aj/Buffer/git-clones/myobeam/jag-freertos-revA/src/main.c")
  cmake-ide--set-flags-for-file(nil #<buffer main.c>)
  #[257 "\301\300�\"\207" [nil cmake-ide--set-flags-for-file] 4 "\n\n(fn X)"](#<buffer main.c>)
  mapc(#[257 "\301\300�\"\207" [nil cmake-ide--set-flags-for-file] 4 "\n\n(fn X)"] (#<buffer main.c> #<killed buffer> #<killed buffer>))
  cmake-ide--on-cmake-finished()
  #[514 "\300\301!\210\302 \207" [cmake-ide--message "Finished running CMake" cmake-ide--on-cmake-finished] 4 "\n\n(fn PROCESS EVENT)"](#<process cmake> "exited abnormally with code 1\n")

**Comment by myrgy** [comment]
@atilaneves , plezse take a look at @dlyr cmake-ide branch.
https://github.com/dlyr/cmake-ide/tree/wip_project_key

It might be great to have this fix in master branch!
Thank you in advance.

**Comment by atilaneves** [comment]
@myrgy I just commented on the PR. It'll probably be merged soon.

**Comment by myrgy** [comment]
https://github.com/atilaneves/cmake-ide/pull/141 was merged, hence closed
