### ISSUE TITLE
Default to Ninja?

### ISSUE THREAD

**Issue by binary132** [atilaneves/cmake-ide#146]
Hi, I noticed that when I run `cmake-ide-compile` with `((nil . ((cmake-ide-build-dir . "build"))))` in `.dir-locals.el`, if I have already created the build using `cmake .. -G Ninja`, it uses Ninja and works fine.  But, if I don't have the `build` directory set up already, then `cmake-ide-compile` defaults to use `make`.  Is it possible for me to tweak it so that `cmake-ide-compile` defaults to Ninja, falling back to the normal platform default if ninja is not defined?

**Comment by atilaneves** [comment]
Yes, somebody added that. You just have to set `cmake-ide-cmake-opts`.
