### ISSUE TITLE
Qt generated header files (in *_autogen/include/*) are not detected

### ISSUE THREAD

**Issue by krofna** [atilaneves/cmake-ide#147]
.h file generated from .ui file by `set(CMAKE_AUTOUIC ON)` doesn't seem to be detected so flycheck shows bunch of errors

**Comment by atilaneves** [comment]
I haven't written Qt code in years. I don't remember `CMAKE_AUTOUIC` existing then. Do these headers appear in the `compile_commands.json` file generated by CMake?

**Comment by krofna** [comment]
`-I/tmp/cmakerq0UZW/ChApp_autogen/include` is there.

**Comment by atilaneves** [comment]
@krofna But you don't see `/tmp/cmakerq0UZW/ChApp_autogen/include` in `flycheck-clang-include-path`?

**Comment by krofna** [comment]
It's there. I just noticed that I actually have to remove the `#include "ui_mainwindow.h"` line after `cmake-ide-compile` and write it again for it to take effect; just running`flycheck-buffer` or making any other change in the file is not enough. So it's definitely not a bug in cmake-ide.

**Comment by Thaodan** [comment]
Is this fixed? I try cmake-ide with a qt based project and get similar errors.

**Comment by atilaneves** [comment]
@Thaodan It was closed by the submitter.
