### ISSUE TITLE
Guard all extern defun

### ISSUE THREAD

**Issue by dlyr** [atilaneves/cmake-ide#149]
Hello,
I propose to "guard" all defun callable by external module to check whether the current buffer is part of a cmake project.
This could be done for instance by checking if project-dir is not null as a first instruction in these function.
here is the list of concerned functions 
```lisp
cmake-ide-maybe-run-cmake ()
cmake-ide-run-cmake ()
cmake-ide-load-db ()
cmake-ide-rdm-executable ()
cmake-ide-set-compiler-flags (buffer flags includes sys-includes)
cmake-ide-delete-file ()
cmake-ide-compile ()
cmake-ide-maybe-start-rdm ()
```
I propose also to check or set correct "env" for test function, since some tests assume some behavior that would not be kept with theses new checks, for instance `test-all-vars-ccache-alt ()` would need something like `(cmake-ide-project-dir "/tmp"))`

I could try it and submit a PR if I get positive feedback to this proposal.

**Comment by atilaneves** [comment]
Hi @dlyr, thank your for submitting this. What issues would your proposal address? i.e. what doesn't work now that would if this were implemented?

**Comment by dlyr** [comment]
Hi @atilaneves, for instance, with current master version, when I open a bare file.c, I have an lisp error 
 (wrong-type-argument stringp nil)
from  expand-file-name(nil "my/pool/build/dir")
That's because of one of my last modification that use a "nil" build dir if no cmake-list found. But in fact this "hack" was added to allow tests to run without defining `project-dir` for instance.
So I would prefer to have correct guards, and add for instance `(cmake-ide-project-dir "/tmp")` or `(cmake-ide-build-dir "/tmp")` to allow tests to pass.

**Comment by atilaneves** [comment]
@dlyr Really? I just upgraded cmake-ide and opened a single .c file and didn't see that message.

**Comment by dlyr** [comment]
do you have `(setq cmake-ide-build-pool-use-persistent-naming t)` ?

**Comment by atilaneves** [comment]
@dlyr No. You're possibly the only person who sets that ;)

**Comment by dlyr** [comment]
@atilaneves really ? i think it's awesome : reuse previous session builds (without dir-locals override) and adapts to cmake-opts (like having one debug and one release build dir coexisting for the same project).
Is there another way to do that ?

**Comment by dlyr** [comment]
@atilaneves anyways, without persistent nameming, cmake-ide still create a build dir for your non cmake .c file, right ? with guards this will not happen anymore.

**Comment by dlyr** [comment]
One question about build-dir
I see user variables `cmake-ide-build-dir` and `cmake-ide-build-dir-pool`
Also when using a relative `cmake-ide-build-dir`, `cmake-ide-project-dir` is used as parent whenever `cmake-ide-build-dir-pool` is set. Is that the correct behavior ?

**Comment by atilaneves** [comment]
@dlyr Even I don't know what the correct behaviour is anymore, especially since I didn't introduce `cmake-ide-build-dir-pool`. That functionality _really_ needs some tests.

**Comment by atilaneves** [comment]
@dlyr Even I don't know what the correct behaviour is anymore, especially since I didn't introduce `cmake-ide-build-dir-pool`. That functionality _really_ needs some tests.

**Comment by dlyr** [comment]
Well as I understand there is two ways to set build directory : 
- set `cmake-ide-build-dir`
- let `cmake-ide` compute a build dir

If `cmake-ide-build-dir` is set, either it's an absolute path, so use it, either it's relative, then use `project-dir` as root
If `cmake-ide` compute the build dir, two other variable enter in the computation : `cmake-ide-build-pool-dir` and `cmake-ide-build-pool-use-persistent-naming`
if `cmake-ide-build-pool-dir` is set use this directory as root directory, else use `/tmp` or equivalent
if `cmake-ide-build-pool-use-persistent-naming` is `'t` compute a build dir depending on `projet-dir` and `cmake-opts`, else use a tmp name (changing with each emacs session).

Do you think thes behavior is fine ? If it's ok, I could send the PR and add tests.

**Comment by atilaneves** [comment]
@dlyr I _think_ so... I've never used `cmake-ide-build-pool-dir` (and am unlikely to every do so). Please add the tests with the behaviour as you understand it. Thanks.

**Comment by dlyr** [comment]
I continue to improve my version, but I still have some troubles.
For instance when I open a file from a cmake projects, some includes could be from system or other place out of any cmake project, which break call to cmake-ide--get-build-dir since emacs default-directory is out of the cmake project directory structure. 
In previous version, a global variable build-dir keep the "last" valid build-dir and use this for the visited file, I remove this since it do not allow to have multiple open project without .dir-locals.el, and also could be a bit weird ... but now I'm not sure, it may be necessary for rtags to add out of project files (right now I'm not confortable with idb and rtags code).
So if the expected behavior of cmake-ide is to do nothing when parsing an out of project file (during the parsing of an in project file), I could guard the function to ignore them. Else, I think to add something as "last-valid-build-dir" to use it as a build dir for these file.

**Comment by atilaneves** [comment]
"So if the expected behavior of cmake-ide is to do nothing when parsing an out of project file" - I would say so. The other packages aren't disabled, flycheck and rtags should work, but there's no way to set compiler flags so cmake-ide shouldn't.

**Comment by dlyr** [comment]
Sounds good to me ... I hope I have enougth time to create the PR soon ;)
