### ISSUE TITLE
cmake-ide-setup change

### ISSUE THREAD

**Issue by netromdk** [atilaneves/cmake-ide#15]
First of all, I like your solution a lot and it's really nice being able to auto-complete and flycheck my fairly large work projects with `cmake-ide` now. I tried so many different things before..

One thing I noticed is that in `cmake-ide-setup` you use `c-mode-common-hook`, which should be fine but there are some major modes that derive from `c-mode`, like `php-mode`, but it's not expected behavior that it also tries to find/run cmake and setting flags for those files.

Perhaps an optional list of modes could be supplied to `cmake-ide-setup` so that it only hooks up to those, and if nothing is given then it uses `c-mode-common-hook` as it does now?

**Comment by atilaneves** [comment]
`php-mode`? Really??? I had no idea.

I've had problems with this running for D projects because of the same thing. I guess I can always (just this once) copy+paste and run for only C and C++.

**Comment by netromdk** [comment]
Yes, not exactly what's exacted. But it'd work if specifically enabling for C/C++ modes.

**Comment by atilaneves** [comment]
Closed with [this commit](https://github.com/atilaneves/cmake-ide/commit/852e0a0f48a1d3c18135ab94a34215bd19c02505)
