### ISSUE TITLE
Prevent auto run cmake for non cmake projects

### ISSUE THREAD

**Issue by vikigenius** [atilaneves/cmake-ide#150]
I am working on a non cmake project using the WAF build system. It does generate a compile_commands.json so everything works good, except for the triggering of cmake when i save files, which causes error messages to appear.

How can i turn off this functionality or maybe create a custom command to run?

**Comment by atilaneves** [comment]
That should have been fixed by a recent PR. Could you please check that you still see the issue with the latest version from MELPA?

**Comment by vikigenius** [comment]
I got the latest from Melpa

It is still happening. Maybe i am not understanding the expected behavior. Since it is a non cmake project it doesn't use CmakeLists.txt.

However from Messages buffer i can see that it is trying to run cmake on save after creating a new file.
I just want to stop this from happening at all or maybe change the command from cmake to waf if possible.

**Comment by dlyr** [comment]
Could you post a minimal bug report example so I could check ?
Also if you don't need any cmake feature, you could simply disable cmake-ide ?

**Comment by vikigenius** [comment]
cmake-ide is quite useful for me since it takes care of setting include path locations and all the flycheck/rtags setup automatically. My build system just generates compile_commands.json, so i suppose it is using that instead of cmakelists.txt.

**Reproducing:**

1. Use any non cmake build system which can generate compile_commands.json. I am using [waf](https://github.com/waf-project/waf).

2. Set cmake-ide-build-dir and cmake-ide-project-dir in dir-locals.el

3. Navigate to any source file in project, cmake will automatically start rtags and setup include paths and flycheck, irony.

4. Create a new file and save, cmake-ide tries to execute cmake automatically and throws an error message saying that cmake could not find cmakelists.txt. 

I know that i can simply ignore the error and continue, but i would like to stop cmale-ide from executing the cmake command on save.

**Comment by atilaneves** [comment]
@vikigenius Please create a demo project with `.dir-locals.el` and all on github so that it can be investigated. I have 0 experience with waf.

**Comment by vikigenius** [comment]
Here is the simple project I have created with waf:  [waf-test](https://github.com/vikigenius/waf-test/tree/master)

**Reproducing:**

1. Clone the repo and build using the following commmands (I have already included the waf script, no need to install locally):
```
./waf configure
./waf build
```
2. Verify that compile_commands.json has already been generated in the generated build directory

3. Change cmake-ide-build-dir and cmake-ide-project-dir in dir-locals.el, i have included the example file, change it to reflect paths in your system.

4. Navigate to any source file in project, cmake will automatically start rtags and setup include paths and flycheck, irony.

5. Create a new file and save, cmake-ide tries to execute cmake automatically and throws an error message saying that cmake could not find cmakelists.txt can be found in the cmake buffer.

**Comment by atilaneves** [comment]
@vikigenius Thank you for putting this together. I'll take a look when I have time.

**Comment by dlyr** [comment]
Hi, if you could give a try to no_cmake_fix branch of https://github.com/dlyr/cmake-ide.git
The test you propose works for me with this version, but since I have done some other modifications, it will really help to have other user test it before PR.

**Comment by vikigenius** [comment]
@dlyr I am away for a few days. I will test once i get back. Were you able to reproduce the issue from my example?

**Comment by dlyr** [comment]
@vikigenius Yes, with master i have a cmake error message saying that there is no CMakeLists.txt
With my branch, no error message, but rtags is still working.
