### ISSUE TITLE
Get target executable from cmake

### ISSUE THREAD

**Issue by dlyr** [atilaneves/cmake-ide#152]
Hi,
I'm thinking of a new feature that catch automatically the target executable from cmake run. 
I may have found a solution : use `cmake -G "CodeBlocks - Unix Makefiles" ...`
which generate a .cbp file, with the following information's :
```xml
<Target title="program_name">
          <Option output="output_dir" prefix_auto="0" extension_auto="0"/>
          <Option working_dir="output_dir"/>
          <Option object_output="./"/>
          <Option type="1"/>
          <Option compiler="gcc"/>
...
```
Maybe this file could be parsed by cmake-ide and provides function access to target lists and run-directory, then the user can call a command to list and choose one of these target to execute.
I'm not sure on how to do that, nor if it's a good way to achieve, but I would love launching easily my program from emacs.

**Comment by atilaneves** [comment]
This is partially covered already by `cmake-ide-compile-command`

**Comment by dlyr** [comment]
@atilaneves, not sure to see how. Do you mean I can add a special run target in my CMakeLists.txt and then use `cmake-ide-compile-command` to run it ?
What I have in mind in something like running the process from emacs, but I need to get exec name from compilation process.

**Comment by atilaneves** [comment]
e.g.

```elisp
(setq cmake-ide-compile-command "make && cd /path/to/build && ./myexe)
M-x compile
```

I understand trying to get the binary info from CMake itself but it's just too much work to implement when you can use directory-local variables.

**Comment by dlyr** [comment]
@atilaneves I have do a simple version of what I have in minds, not perfect, but work for me.
It's available here : [rt](https://github.com/dlyr/rt)
