### ISSUE TITLE
GNU make support

### ISSUE THREAD

**Issue by TediCreations** [atilaneves/cmake-ide#153]
I am new to EMACS and LISP but I would like to learn both. Right now I use EMACS at a basic level.
I would like to add GNU make support to your package. I would welcome any thoughts you have on this.

**Comment by dlyr** [comment]
Hi @TediCreations, could you be more precise ? As far as I understand, a central point of cmake-ide is compile-commands.json to set rtags. How do you want to use GNU make to produce such a file ?
Btw cmake could use GNU make as compile manager (as I usually do).

**Comment by atilaneves** [comment]
@TediCreations Support make as a source of compiler flags? That's not something I want this package to do. If you mean to use make to build, that can already be done.

**Comment by Nidish96** [comment]
Just to add to this, bear can be used to generate compile_commands.json - so I think that was what the OP was getting at. This functionality already exists in cmake-ide. I think this can be closed.
