### ISSUE TITLE
Do not automatically start cmake-ide

### ISSUE THREAD

**Issue by simonpp** [atilaneves/cmake-ide#160]
Is it possible to prevent cmake-ide from automatically starting rtags indexing once a file belonging to a CMake project is opened? E.g. starting cmake-ide for a project only upon request, for example when `cmake-ide-run-cmake` is called?

**Comment by atilaneves** [comment]
Yes, don't call `(cmake-ide-setup)` and do it in a custom fashion.

**Comment by atilaneves** [comment]
Yes, don't call `(cmake-ide-setup)` and do it in a custom fashion.

**Comment by simonpp** [comment]
Thanks
