### ISSUE TITLE
cmake-ide reports error when loading emacs

### ISSUE THREAD

**Issue by LukeXuan** [atilaneves/cmake-ide#162]
I'm currently using the spacemacs with persp-mode and cmake-ide. Frequently, when I start the emacs and load a "layout" with opened c/c++ file in it. The cmake-ide will report some error and the loading will halt. The error message is reported below.

```
[persp-mode] Error: Can not autoresume perspectives -- (wrong-type-argument hash-table-p nil)
cmake-ide [Sun Mar 18 10:28:58 2018]: Finished running CMake
error in process sentinel: cmake-ide--get-string-from-file: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil
```

Any thoughts about what can go wrong with it? I'm actually not sure where to report this error.

**Comment by atilaneves** [comment]
I don't know what `persp-mode` is. Your error message from cmake-ide is usually due to the output of running CMake not looking like proper JSON. Is there a `compile_commands.json` in the build directory?

**Comment by LukeXuan** [comment]
Yes there is one, located in `/var/folders/p9/m69k7skn2bv0jjw9g1zyt99r0000gn/T/cmake24515Ucj/`.

As the complete log indicates

```
cmake-ide [Tue Mar 20 13:41:06 2018]: Making directory /var/folders/p9/m69k7skn2bv0jjw9g1zyt99r0000gn/T/cmake24515Ucj
cmake-ide [Tue Mar 20 13:41:06 2018]: Running cmake for src path /some/path/ in build path /var/folders/p9/m69k7skn2bv0jjw9g1zyt99r0000gn/T/cmake24515Ucj/
cmake-ide [Tue Mar 20 13:41:06 2018]: Non-existent compilation DB file /var/folders/p9/m69k7skn2bv0jjw9g1zyt99r0000gn/T/cmake24515Ucj/compile_commands.json
[persp-mode] Error: Can not autoresume perspectives -- (wrong-type-argument hash-table-p nil)
cmake-ide [Tue Mar 20 13:41:08 2018]: Finished running CMake
error in process sentinel: cmake-ide--get-string-from-file: Wrong type argument: stringp, nil
error in process sentinel: Wrong type argument: stringp, nil
```

I listed the file and the JSON is there.

**Comment by atilaneves** [comment]
The log says the file doesn't exist - which means it didn't exist when that message was printed. I can't see how I can help you debug that remotely.

**Comment by LukeXuan** [comment]
Is there a place I can insert code to print of the "ls path" output just before that line of log is executed? It's strange though because I'm printing immediately after the emacs finishing booting(so that I can know the directory).

**Comment by atilaneves** [comment]
You can delete the `cmake-ide.elc` file in your `.emacs.d` and play around with the code as much as you want (or just keep recompiling the file after every edit). You can also `(eval-buffer)` after editing `cmake-ide.el` so the changes are "live".

**Comment by LukeXuan** [comment]
If I'm confident about my understanding and programming in ELisp then I would open a pull request rather an issue. I will have a try anyway, and I think this issue can be closed for now.
