### ISSUE TITLE
cmake-ide-compile results in error message

### ISSUE THREAD

**Issue by DasNaCl** [atilaneves/cmake-ide#167]
Running cmake-ide-compile in a cmake project I encounter the following error:
`Wrong type element: commandp, nil`
What can I do about this? Especially: How can I provide you with more debugging information? I tried running emacs with `--debug-int` without success.

**Comment by atilaneves** [comment]
cmake-ide outputs quite a few messages. Check the messages buffer for more information. Unfortunately with only the error message you pasted above there's not much I can do.

**Comment by DasNaCl** [comment]
Thanks for your very quick response! According to your recommendation I took further looks into it.
Output is like this:

> cmake-ide [Wed May  9 20:01:03 2018]: Making directory /tmp/cmakelRqL0A

> cmake-ide [Wed May  9 20:01:04 2018]: Running cmake for src path /home/dasnacl/project/ in build path /tmp/cmakelRqL0A/
> cmake-ide [Wed May  9 20:01:07 2018]: Finished running CMake
> cmake-ide [Wed May  9 20:01:07 2018]: Non-existent compilation DB file /tmp/cmakelRqL0A/compile_commands.json
> error in process sentinel: cide--idb-file-to-obj: Wrong type argument: hash-table-p, nil
> error in process sentinel: Wrong type argument: hash-table-p, nil
> cmake-ide-compile: Wrong type argument: commandp, nil

I created a compile_commands.json in project's dir myself, which doesn't help either.
Also, I added `nel: Wrong type argument: hash-table-p, nil
> cmake-ide-compile: Wrong type argument: commandp, nil

So clearly, it complains about a missing db file, which I created in first place with cmake, however.
Also, I have a `.dir-locals.el` in `/home/dasnacl/project/` containing `((nil . ((cmake-ide-build-dir . "/home/dasnacl/project/build/"))))`, but no luck.

**Comment by atilaneves** [comment]
Why are you creating `compile_commands.json` yourself?

**Comment by DasNaCl** [comment]
Good question. Removing it fixed it all. Thank you!
