### ISSUE TITLE
A more complete wiki walkthrough for Emacs novices

### ISSUE THREAD

**Issue by akalsi87** [atilaneves/cmake-ide#17]
I saw your CppCon talk and I remembered that I have tried cmake-ide before, but with limited success because I have not used Emacs packages before and have not done much Lisp.

However, I would really like to get it up and running so a Wiki page guiding some one and actually talking about a few gotchas would be immensely helpful!

I could work with you to create something like this if you don't have enough time but the patience to answer my stupid questions.

This is an enhancement.

**Comment by atilaneves** [comment]
Your questions aren't stupid :)
It's hard to do a wiki for this - the main problem being that `cmake-ide` is a facilitator and the "real" work is done by other packages. Which combination of them is up to the user! So first make sure you install e.g. flycheck, autocomplete, autocomplete-clang and rtags. Forget about cmake-ide first and make sure all of these other packages actually work. From then on you shouldn't really have to do anything.

**Comment by akalsi87** [comment]
I was able to get this to work by installing things in the order you specified and everything worked like a charm.

Installing Rtags was a pain because it refused to find Clang so I had to manually type in the ```include_directories()``` call to appease it.
