### ISSUE TITLE
Can't find "dash"

### ISSUE THREAD

**Issue by tinloaf** [atilaneves/cmake-ide#176]
Hi,

I installed `cmake-ide` via MELPA. I enabled it in my `init.el` file as suggested. Now on startup I get the error:

```
Warning (initialization): An error occurred while loading `/home/lukas/.emacs.d/init.el':

File error: Cannot open load file, no such file or directory, dash

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

I'm not sure what's happening there. Does cmake-ide require the `dash` shell to be installed? It is installed on my system… Or is that some other file missing?

Thanks for any help,

Lukas

**Comment by jian-lin** [comment]
@atilaneves Please add dependency dash to Package-Requires so that all dependencies are automatically installed when this package is installed from MELPA.

**Comment by atilaneves** [comment]
> @atilaneves Please add dependency dash to Package-Requires so that all dependencies are automatically installed when this package is installed from MELPA.

PR welcome.
