### ISSUE TITLE
feature request: allow specifying parameters passed to cmake

### ISSUE THREAD

**Issue by bloerwald** [atilaneves/cmake-ide#18]
use case: cmake script tries to find dependencies via non-environment variables

can be worked around by pre-running cmake with parameters so that they are cached for the parameter-less invocation by cmake-ide

**Comment by atilaneves** [comment]
The parameters are project-specific though, which is why I punted and had it so users have to run cmake as they want at least once. How do you suggest to specify the parameters?

**Comment by bloerwald** [comment]
I figured that that was the motivation for not having it. Some of the parameters are surely not entirely project specific (that would be two parameters for all but one project for me (all plugins for the same framework)). Other than that, one could do the directory-local approach, I would foolishly assume.

I just saw that I completely missed the "except for the first time to specify options" remark in the readme. Seeing that would probably have done the job and make me use that directory-local ide-path to begin with.
