### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by rileyrg** [atilaneves/cmake-ide#186]
I need some help getting this to work. Maybe missing something. I had already set up my own rtags/xref/company system for flycheck, navigation and completion but it simply wasn't working properly: unresolved symbols, includes not found according to flycheck but discovered via company-rtags. So I commented all this out and am trying your IDE suggestions.

Right, so I ran (cmake-ide-setup). Now what? There is nothing of consequence in my c-mode buffer. No completion, xref is still default and its backend functions are only '(etags--xref-backend). 

I have set my cmake-ide-project-dir via .dir-locals.el and verified the buffer local value.
```
(
 (nil . (
         (eval . (add-to-list 'flycheck-clang-include-path (concat (projectile-project-root) "include")))
         (cmake-ide-project-dir . "/home/rgr/development/arduino/Blink-PlatformIO")
         (cmake-ide-build-dir . "/home/rgr/development/arduino/Blink-PlatformIO")
)))



```

rtags is compiled and installed from source and my rdm systemd service is available and is known to work from my previous setup-: the source install of company-rtags, flycheck-rtags is on the load-path.

I should add this is currently a Makefile project (not cmake) but I do have my compile_commands.json in the project directory courtesy of "compiledb make".

When I open my src/main.cpp I do get this indicating cmake-ide is alive.

> cmake-ide [Sun Mar  3 10:47:22 2019]: Converting JSON CDB /home/rgr/development/arduino/Blink-PlatformIO/compile_commands.json to IDB
> cmake-ide [Sun Mar  3 10:47:22 2019]: Setting flags for file /home/rgr/development/arduino/Blink-PlatformIO/src/main.cpp
> 

But no completion (company is my default and company-rtags was added in my version)  , no navigation (I had added rtags-xref to xref backends in my own version)

You're onto a good things here. rtags is the ONLY way to go.

**Comment by atilaneves** [comment]
>  should add this is currently a Makefile project (not cmake)

That would be the problem right there. As implied by the name, `cmake-ide` only supports CMake projects. It *could* be refactored to read a compilation database regardless of the type of project, and is something I've been wanting to do for a while. But it's not trivial, which is why I haven't yet.

**Comment by rileyrg** [comment]
Ok, in your notes you specifically mention non cmake projects working if we
have a commands-json.  But fair enough.

As it happens I got it working properly with Arduino by hard coding the avr
include directory into my rdm systemd service file.  Rtags working like a
dream now.

**Comment by atilaneves** [comment]
> Ok, in your notes you specifically mention non cmake projects working if we have a commands-json

I'd completely forgotten about that and had to look at the README and git history to have an inkling of what past me was talking about!

I'm not sure how I'd go about reproducing your issue though.
