### ISSUE TITLE
Comment on compatibility/overlap with emacs-lsp/emacs-eglot

### ISSUE THREAD

**Issue by sunbubble** [atilaneves/cmake-ide#197]
Hi there. Can you comment on the compatibility, functionality overlap and/or eventual integration of cmake-ide and more recent language server protocol based packages such as [lsp-mode](https://github.com/emacs-lsp) or [eglot](https://github.com/joaotavora/eglot). I couldn't find any reference to either.

Thank you in advance

**Comment by dlyr** [comment]
I use both of them (currently eglot with ccls), to this end I had disable rtags/flycheck from cmake-ide.
So cmake-ide manages cmake command, build directories (for instance one for release, one for debug, one per git branches).
In conjuction with https://github.com/dlyr/rt I also use cmake-ide to determine which are the target I can run

**Comment by sunbubble** [comment]
Thanks for the quick response. Good to know that there are no major conficts. I have a small follow-up question, do you leverage the same system for debugging? [dap-mode](https://github.com/emacs-lsp/dap-mode) looks like a very promissing fit.

**Comment by dlyr** [comment]
I do not know about dap-mode, for debugging I personally use gdb (with gud in emacs, run facilitated with rt.el)

**Comment by atilaneves** [comment]
LSP didn't exist when I started this project, so I can't comment. As for debugging, I use gdb inside emacs.

**Comment by sunbubble** [comment]
> LSP didn't exist when I started this project, so I can't comment.

I was curious about your thoughts on how cmake-ide and LSP could play together.

**Comment by dlyr** [comment]
For myself, I add options to totally disable rtags and flycheck, then I add a sentinel to link compile_commands.json into project dir, and use eglot+ccls for code navigation and complete (or lsp+ccls)
eglot, lsp and ccls are not always stable, and I still have false flymake errors reported, sometimes ccls crashes, so I had to reboot it to have code navigation.

To sum up cmake-ide act as a cmake project manager (compile in debug/release, with different build dir base on git branches ...) and lsp/eglot/ccls for code navigation and complete.

Check https://github.com/dlyr/cmake-ide/tree/cmake-only
and 
https://github.com/dlyr/rt  (well the sentinel is not working anymore, I have to find a patch)

**Comment by atilaneves** [comment]
> > LSP didn't exist when I started this project, so I can't comment.
> 
> I was curious about your thoughts on how cmake-ide and LSP could play together.

I'd have to look into it and I really don't have the time. It doesn't help that I hardly ever write C or C++ these days.
