### ISSUE TITLE
Functions signature for autocompletion

### ISSUE THREAD

**Issue by LaP0573** [atilaneves/cmake-ide#20]
This is not really issue-worthy, but I don't really see how to tackle this. cmake-ide is working fine so far, but my autocompletion (with auto-complete) is quite bland, there's no method signature for example, only the name of the function.

How do you get function signature for your autocompletion, using cmake-ide ? (similar to what was shown on your presentation)

**Comment by atilaneves** [comment]
I was using company-mode during the presentation, you can always try that.

**Comment by LaP0573** [comment]
Oh you're right, thanks a lot, seems that company now displays the signature which is great, unlike auto-complete.

However, two quick last questions (and sorry for being off-topic) :
- The signature of the function is displayed in the company tooltip and at the bottom of Emacs, however as soon as I press enter to validate the completion (and as I start typing in the arguments themselves), this information disappears. Would it be possible to keep it somewhere on the screen ?
- Aside from a problem with one of my libraries (for some reason flycheck doesn't find the header although it compiles just fine), I can't get completion for OpenGL (which is my main goal right now). The headers are fine but there's no autocompletion whatsoever. When I enable functions-args-mode and try a completion for the first time semantic takes a loooong time indexing and browsing files, so I assume it's looking for OpenGL, but once it's done I get no autocompletion at all. Any idea ?

**Comment by atilaneves** [comment]
Clang does that sometimes for headers and I don't even know what's going on there. As for function signatures, that's up to company-mode. I've seen yasnippet used for this as well in another project.
