### ISSUE TITLE
ff-other-file-name is removed in emacs 28

### ISSUE THREAD

**Issue by Thaodan** [atilaneves/cmake-ide#208]
Instead of `ff-other-file-name` ->  `ff-find-the-other-file` should be used.

The change was made in:
http://git.savannah.gnu.org/cgit/emacs.git/commit/?h=master&id=c9655fcb47da8a104eb7b5eb7a3d0b4a6ba26fc3

**Comment by Thaodan** [comment]
Note: I will fix, that issue is for me to track the issue.

**Comment by atilaneves** [comment]
Thanks!
