### ISSUE TITLE
Way to query variables?

### ISSUE THREAD

**Issue by jkordani** [atilaneves/cmake-ide#213]
One thing I've always wanted to do was compile the whole cmake state so that I could inspect cmake variable values and settings without having to add print statements to CMakeLists.txt

Is such a thing possible?  The blurb on melpa about this project says so but I can't figure out how to do it

**Comment by atilaneves** [comment]
Can't you look in CMakeCache.txt?

**Comment by jkordani** [comment]
I can now!!! Today I learned.....  Thank you!
