### ISSUE TITLE
target_include_directories not integrated when wrapped in if/else for cmake_build_type

### ISSUE THREAD

**Issue by borysn** [atilaneves/cmake-ide#215]
came to this project because of include path errors in emacs which are frustrating because they prevent other error/syntax checking. i just need `target_include_directories` to be integrated in emacs, but i am having an issue when the statement is wrapped inside an if/else which splits up the build by `CMAKE_BUILD_TYPE` 

the project has the following in it's `CMakeLists.txt`

``` cmake
if (${CMAKE_BUILD_TYPE} STREQUAL "release" OR
    ${CMAKE_BUILD_TYPE} STREQUAL "debug")  
 ...
  ## add libevdev include directory
  target_include_directories(kbdmoused PRIVATE /usr/include/libevdev-1.0)
elseif (${CMAKE_BUILD_TYPE} STREQUAL "test")
...
endif()
```

created a `makefile` which sets up and runs the cmake builds, with the following commands

``` make
release:
	@cmake -S . -B $(build-dir)/$(release-dir) -DCMAKE_BUILD_TYPE=release -DCMAKE_EXPORT_COMPILE_COMMANDS=1
	@cmake --build $(build-dir)/$(release-dir)

debug:
	@cmake -S . -B $(build-dir)/$(debug-dir) -DCMAKE_BUILD_TYPE=debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1
	@cmake --build $(build-dir)/$(debug-dir)

test:
	@cmake -S . -B $(build-dir)/$(test-dir) -DCMAKE_BUILD_TYPE=test
	@cmake --build $(build-dir)/$(test-dir)
```

not sure how to properly setup cmake-ide so that the `target_include_directories` statement is properly handled. i have a simpler project which doesn't split up builds in this way, and the target_include_directories works fine there. 

also, it seems that cmake-ide is not accounting for being used with multiple projects, as loading the more complex project breaks the syntax/error checking for the other. it seems that cmake-ide is set in stone with a single process for a simple type of project configuration, instead of being more dynamic and scanning for things. 

is there a way to properly configure cmake-ide for this type of scenario? am i missing something? 

here are links to the full configurations if it's necessary to see

[CMakeLists.txt](https://gitlab.com/commet-alt-w/kbdmouse/-/blob/dev/CMakeLists.txt)
[makefile](https://gitlab.com/commet-alt-w/kbdmouse/-/blob/dev/makfile)

any help would be great, thanks

**Comment by atilaneves** [comment]
cmake-ide works by running cmake, reading the JSON compilation database, then setting various variables for other Emacs packages like rtags and flycheck. CMake's target_include_directories would, via the compilation database, end up setting `flycheck-clang-include-path` for instance.

There's `cmake-ide-cmake-opts` to control what options are to be passed to cmake, like `-DCMAKE_BUILD_TYPE=Debug`.

> created a makefile which sets up and runs the cmake builds, with the following commands

I don't understand why one would want to do that. The usual way is to have a different build directory for each build type, run cmake from there and never look at it again.

**Comment by borysn** [comment]
@atilaneves ended up figuring out `flycheck-clang-include-path`, was actually trying `flycheck-gcc-include-path` before. it's just weird that sometimes it worked without setting those values and sometimes not, that caused some confusion. will have to look into integrating `cmake-ide-cmake-opts` with my work flow in emacs. 

> I don't understand why one would want to do that. The usual way is to have a different build directory for each build type, run cmake from there and never look at it again.

maybe sometimes for already established projects, but this is exactly what my makefile does. it's just a simple and effective convenience. easier to type `make` or `make debug` than any of the entire cmake commands. 

cmake won't redo all it's work for source file changes or even adding new source files. and as a larger project is beginning to take shape, it's natural cmakelists.txt begins to grow. also, there some changes to cmakelists.txt which won't propogate to makefile generation after it's already generated build files. 

thanks for the reply, cmake-ide has helped a lot with my workflow.
