### ISSUE TITLE
CMake options in cmake-ide--run-cmake-impl

### ISSUE THREAD

**Issue by donaldmunro** [atilaneves/cmake-ide#22]
It may be a useful enhancement to allow users to have a variable to set options to cmake in  cmake-ide--run-cmake-impl. One use case is a Android CMake project ([android-cmake](https://github.com/taka-no-me/android-cmake/)) which requires specifying the Android toolchain as a -D option which cannot be placed in the CMakeLists.txt file eg:

cmake -DCMAKE_TOOLCHAIN_FILE=../android-cmake/android.toolchain.cmake -DANDROID_NDK=/opt/android-ndk-r10e  -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="armeabi-v7a with NEON"  -DANDROID_NATIVE_API_LEVEL="android-21" ..

The rest of the flags other than CMAKE_TOOLCHAIN_FILE can probably be specified in the CMakeLists.txt file, but CMAKE_TOOLCHAIN_FILE must be specified as a cmake option.

As a workaround its obviously easy to edit cmake-ide--run-cmake-impl.

**Comment by atilaneves** [comment]
The way I went about this is to require the user to specify the flags they need the first time.
