### ISSUE TITLE
cmake-ide fail to set the correct flags in any header file

### ISSUE THREAD

**Issue by sezaru** [atilaneves/cmake-ide#31]
Whenever I enter some buffer that is a hpp file and not a cpp, cmake-ide seems to set wrong flags to rtags and flycheck.

Both stop working, but flycheck gives me errors like:
    clang: error: no such file or directory: 'CMakeFiles/Evaluation.dir/src/Measures/BoundaryPrecision.cpp.o' 

The problem, as far as I understand, is that whenever the file cmake-ide is setting the flags is a header file, it will simply include all the possible .o files of the project to it, and since these files haven't been compiled yet, they doesn't exist and so I get the error.

I guess a cmake-ide-compile would generate the .o files, but it is a little cumbersome to do it every time I open the project or create a new file in it.

And even with cmake-ide-compile, the problem persists whenever I have a add_subdirectory command, for example, in my project, the root CMakeLists.txt have this:
    add_subdirectory (libs)

Inside the libs directory, exists another CMakeLists.txt, this one contains:
    add_subdirectory (Evaluation)

And inside Evaluation I have a new project which will generate a evaluation lib with add_library that is used in my root project.

The problem in this case is that cmake-ide seems to ignore this directory structure, in the error example:
    clang: error: no such file or directory: 'CMakeFiles/Evaluation.dir/src/Measures/BoundaryPrecision.cpp.o' 

the path is incorrect, the correct one is:
    libs/Evaluation/CMakeFiles/Evaluation.dir/src/Measures/BoundaryPrecision.cpp.o
inside the temporary directory:
    /tmp/cmake8265867v

If you can't reproduce this, I can create a small cmake project with the problem to send to you, but it should fire with any add_subdirectory in CMakeLists.txt

**Comment by atilaneves** [comment]
I can reproduce it and have been running into the bug myself. I still haven't figured out the best thing to do for headers, but this needs fixing.
