### ISSUE TITLE
option for not starting rdm?

### ISSUE THREAD

**Issue by blaenk** [atilaneves/cmake-ide#35]
I'm managing rdm via systemd, so it's running, but cmake-ide checks if `(get-process "rdm")` returns true and if not, starts rdm itself. It always seems to evaluate to false, and so starts it itself, even though I'm running rdm as user. The original rdm from systemd then seems to shutdown, leaving me without an rdm once I close emacs since rdm is a child process of emacs when cmake-ide launches it.

I don't know if there's a function similar to `get-process` that can see outside of the emacs process tree (if that's what the problem is). Doing `(shell-command "pgrep rdm")` seems to have its indented effect on my end, but I don't know if that's desirable.

**Comment by atilaneves** [comment]
I'll see what the best option is. The easiest is to have a variable telling it to never bother trying. The problem with `shell-command` is that it's not portable.

**Comment by blaenk** [comment]
Yeah I figured. I was thinking a variable would probably be the simplest way as well. Can probably abstract the check out to a function that does the check either for the variable being set or `get-process` check if not. Thanks for considering this!

**Comment by blaenk** [comment]
Confirmed working. Thanks!
