### ISSUE TITLE
Option to disable trying to find cpp file of header

### ISSUE THREAD

**Issue by sezaru** [atilaneves/cmake-ide#36]
CMake-ide uses ff-find-other-file to find the cpp file of a header, but in my project it always fails to find and in the end include all the flags of the project.

the problem is that this search locks emacs for almost 4 seconds, so every time I open a hpp now it locks emacs for this period.

**Comment by atilaneves** [comment]
I thought of doing that yesterday but ran out of time. It's a good feature to have, I'll see if I can get to it today.

**Comment by atilaneves** [comment]
The two variables are called `cmake-ide-header-search-other-file` and `cmake-ide-header-search-first-including`
