### ISSUE TITLE
Allow change the compiler when running cmake configure

### ISSUE THREAD

**Issue by sezaru** [atilaneves/cmake-ide#42]
cmake-ide will always use the default compiler set in environment CC and CXX variables, normally this will mean gcc.

It would be better if cmake-ide allowed the user to be able to change it to another compiler, say clang for example, without changing the CC and CXX variables.

The reason for that is when your project have precompiled headers (use cotire for example), irony syntax checker will fail since it will try to use the specific compiled files for gcc (the normally default compiler) with clang (see this issue for more about it: https://github.com/Sarcasm/irony-mode/issues/277 ).

The fix seems easy enough, with this simple change I can make cmake-ide always use clang:
Change
    (start-process cmake-ide-cmake-command "*cmake*" "cmake" "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" project-dir))))
to
    (start-process cmake-ide-cmake-command "*cmake*" "env" "CC=clang-3.6" "CXX=clang-3.6" "cmake" "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" project-dir))))
in the cmake-ide--run-cmake-impl function.

Sure, the actual fix should permit changing to whatever compiler the user wants, instead of fixind it to clang as shown above.

Thanks

**Comment by atilaneves** [comment]
Yeah, always using clang would not be a good idea. The user might not even have it installed. This is better handled by the user running cmake once themselves with whatever variables they want. AFAIC this is a dup of #22 so I'm closing it.
