### ISSUE TITLE
Problems with cmake-ide-dir variable

### ISSUE THREAD

**Issue by sdeber** [atilaneves/cmake-ide#48]
I have a weird problem with this variable. Say I try to set up my project with existing source and CMakeFiles.txt for the first time. First of all I leave this variable empty and run cmake-ide-run-cmake. Then everything works. From the RDM log, I can see rtags was indexing my project.

However, if I set the cmake-ide-dir variable first, then run cmake-ide-run-cmake, rtags will not index my project at all? Is this a bug or I have to run the command without setting up this variable for the very first time for each project?

**Comment by atilaneves** [comment]
`cmake-ide-dir` is the build directory, not the source. I should probably rename it. I think that's your issue anyway, I'm making an educated guess. The way it's supposed to be used is you set it to where you want the build to happen so it doesn't have to recompile everything from scratch. So, ideally, it should be set before using cmake-ide. In fact, right now the way to use cmake-ide is to run cmake manually from the build directory first. I still need to get around to enabling doing it from emacs itself.

I hope that helps. If not, I need more information that what was given and exact steps to reproduce the issue.

**Comment by sdeber** [comment]
In fact, I have done exactly what you have said here.

1. Create the build folder somewhere, in my case, it is directly under the project folder "~/Project/build"
2. Run cmake under the build folder.
3. Use directory-local variable in the source folder to set cmake-ide-dir to the build folder
4. open any .cpp/.h file in the source

At this stage, I can see (from the minibuffer messages) cmake ide was calling rc. However, the project was not indexed by rtags. By doing "rc --project", it outputs nothing. 

On the other hand, if I do not set the variable at all, and I just open the CMakeFiles.txt, then use cmake-ide-run-cmake to run it. Then I can see the project was build in a tmp folder at the same time, rtags started to index my project.

**Comment by atilaneves** [comment]
Is is an open source project? I can't debug it if I can't reproduce the issue.

**Comment by sdeber** [comment]
Unfortunately no. Let me try more. I will get back to you if I manage to find something.

**Comment by ennokde** [comment]
The cmake-ide-dir path has to be either relative to the project directory or absolute. The project directory is the one containing the top-level CMakeLists.txt.
Assuming that ~/Project/CMakeLists.txt is the top level CMakeLists.txt you only have to put <code>((nil . ((cmake-ide-dir . "build"))))</code> into your .dir-locals.el and it will build in that directory.
If your top-level list is for example ~/Project/src/CMakeLists.txt you will probably have to prepend a "../" accordingly. I did not try this but am pretty confident that it should work.
