### ISSUE TITLE
Unable to set rc executable custom path

### ISSUE THREAD

**Issue by Franzo-** [atilaneves/cmake-ide#49]
My rtags build directory is not in the system path, so I set `cmake-ide-rdm-executable` and `cmake-ide-rc-executable` to the absolute path of the executables. While `rdm` run as expected, `rc` is not found:

`cmake-ide [Tue Mar 15 15:33:56 2016]: Running rc for rtags`
`error in process sentinel: rtags-call-rc: Can’t find rc`
`error in process sentinel: Can’t find rc`

Looking at the code in cmake-ide.el, I suppose the problem is that the `cmake-ide-rc-executable` variable is declared but never used. 
Manually setting the `rtags-path` variable to the path of the directory of `rc` and `rdm` executables solves the problem, but isn't there a way to get this automatically?

**Comment by atilaneves** [comment]
cmake-ide now uses `rtags-calls-rc` instead of calling `rc` directly. I'll delete the variable.

**Comment by Franzo-** [comment]
So the only way to get `rc` working when it is not in the system path is to set the `rtags-path` variable to my custom path?

**Comment by atilaneves** [comment]
Yes. It's an rtags feature, it was wrong of me to intrude.

**Comment by Franzo-** [comment]
Ok, thanks for your help!
