### ISSUE TITLE
Symbol's function definition is void: some

### ISSUE THREAD

**Issue by cdolan** [atilaneves/cmake-ide#53]
It looks like there's an implied package dependency from the use of `some` in [`cmake-ide--is-src-file`](https://github.com/atilaneves/cmake-ide/blob/master/cmake-ide.el#L471). What package does this come from?

**Comment by atilaneves** [comment]
It's in `cl-extra` which should be autoloaded. Which version of Emacs and on which OS? I can't reproduce this.

**Comment by spebern** [comment]
same issue here
emacs version: GNU Emacs 24.5.1
requiring cl before fixes it for me
```
(require 'cl)
(require 'rtags) ;; optional, must have rtags installed
(cmake-ide-setup)
```

**Comment by atilaneves** [comment]
I'm also on Arch Linux and can't reproduce. 'cl is deprecated and there's a `(require 'cl-lib)` right there.

**Comment by BorisCarvajal** [comment]
Same problem
Arch + 24.5.1

**Comment by cdolan** [comment]
I can't speak for others, but I'm using [use-package](https://github.com/jwiegley/use-package) if that makes any difference. Manually adding `(require 'cl)` resolves this issue for me.

**Comment by atilaneves** [comment]
I don't use `use-package`, that might be the difference, I'll try it and report back.

**Comment by BorisCarvajal** [comment]
Tried a minimal dotfile.
```
(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line
(cmake-ide-setup)
```
with cmake-ide-build-dir in a local vars file.
Nothing new.

**Comment by atilaneves** [comment]
@BorisCarvajal I tried your minimal init, nothing went wrong

**Comment by BorisCarvajal** [comment]
Why not just prefix "some" function? using cl-some works flawless.

**Comment by atilaneves** [comment]
@BorisCarvajal PR?
