### ISSUE TITLE
Opening headers is slow.

### ISSUE THREAD

**Issue by parbo** [atilaneves/cmake-ide#59]
Since searching for the source file for a header is unusably slow for me, I disabled it:

  (setq cmake-ide-header-search-other-file nil)
  (setq cmake-ide-header-search-first-including nil)

But it still takes several seconds to open a header file, much longer than a source file.

Here's output from the profiler:

[profiler.txt](https://github.com/atilaneves/cmake-ide/files/258773/profiler.txt)

compile_commands.json is 5-6 MB for my project (which is proprietary, so I can't link it)

**Comment by atilaneves** [comment]
Maybe I can add an option to not even bother setting flags for headers? I can't reproduce this since it's proprietary and figuring out what to do for headers was a pain.

**Comment by sbroberg** [comment]
Would it be possible to use the capabilities of some of the modules that cmake is configuring to perform this action?  For example, if rtags is installed, I'm assuming that it could rapidly locate the relevant cpp file.  Similarly, projectile may be able to narrow the search.

**Comment by bkchr** [comment]
I am seeing the same problem, opening a cpp is blinking fast, but opening a header takes a while.. Are there any new ideas what could be the problem?

**Comment by atilaneves** [comment]
New ideas, no. Just disable some of the strategies for headers. You'll probably not get the flags set correctly though.

**Comment by gnzlbg** [comment]
cmake-ide takes 10-20s to open header files when I edit header-only libraries with it, is this normal / intended ?

**Comment by atilaneves** [comment]
Intended, definitely not. Normal: depends. It's still not clear to me what the best thing to do with headers is, and some of the strategies I came up with trade-off accuracy for speed. As mentioned above, you can configure what the behaviour is, even turning it off for headers completely.

**Comment by gnzlbg** [comment]
@atilaneves 

I have set:

```elisp
  (setq cmake-ide-header-search-other-file nil)
  (setq cmake-ide-header-search-first-including nil)
```

which brings down file opening time from 10-20s to 3-5s when using cmake-ide for headers, yet I still get this `*Messages*`:

```shell
cmake-ide [Thu Oct 12 13:19:30 2017]: Setting flags for file /range-v3/include/range/v3/detail/variant.hpp
cmake-ide [Thu Oct 12 13:19:30 2017]: Could not find suitable src file for /range-v3/include/range/v3/detail/variant.hpp, using all compiler flags
```

IMO 3-5s to open a file is still unacceptable.

IMO trying to tune the heuristic of how much work is done for headers is the wrong approach to solving this problem.

The real question is: why does setting a file flags blocks the UI at all? 

In my opinion, whatever cmake-ide needs to do, it should do in the background, without blocking the UI. If it needs 10-20s to find the file flags, then that's what it needs. But optimizing that is an orthogonal problem to blocking the editor from doing anything else during those 10-20 seconds.

**Comment by atilaneves** [comment]
It blocks the UI because that's how Emacs works - there aren't any threads or async functions, due to its age. If it could be done in the background, it would have been.

As for still blocking - I could add another variable to not apply flags to header files at all. Would that work?

**Comment by gnzlbg** [comment]
That would be a quick workaround.

> It blocks the UI because that's how Emacs works - there aren't any threads or async functions, due to its age. If it could be done in the background, it would have been.

AFAIK emacs does not support threads, but it supports creating processes in the background and communicating with them (this is how the autocomplete async clang plugin works): 

https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html

**Comment by atilaneves** [comment]
It blocks the UI because that's how Emacs works - there aren't any threads or async functions, due to its age. If it could be done in the background, it would have been.

As for still blocking - I could add another variable to not apply flags to header files at all. Would that work?

**Comment by amosbird** [comment]
Hi, I'm seeing this too. I'm curious what flags does cmake try to find for header files?

**Comment by gnzlbg** [comment]
@amosbird it is probably trying to use the same flags than the corresponding `.cpp` implementation file, but to do that it has to find this `.cpp` file first. 

That is hard, because it doesn't exist, so it is probably traversing your whole project directory structure looking for it till there is nothing else that it can do, and then it gives up.

**Comment by amosbird** [comment]
Oh, OK. Do you have any workaround now :) ?

**Comment by atilaneves** [comment]
@amosbird It depends on your configuration. Check the code for `cmake-ide--set-flags-for-hdr-file`.

**Comment by atilaneves** [comment]
@gnzlbg It also does that. But C/C++ doesn't have any mandated naming scheme, and multiple source files can implement a header, so that file might not exist.

**Comment by myrgy** [comment]
Hi @atilaneves 
emacs 26 will have threading
do you think if it's possible to use threads to speed-up cmake-ide?

**Comment by gnzlbg** [comment]
I don’t think speed up is the problem. Blocking the UI is.

When I open a file I want it to open instantaneously and my edits to happen
instantaneously. Whether the plugins take a bit to load or not doesn’t
really matter, but if opening a 50 lines long file blocks the whole editor
for seconds because the plugins must load in order and what not is
something that really pisses me off and the main reason I turn off
cmake-ide.

**Comment by myrgy** [comment]
That's I was talking about - perform flags search in background and avoid UI blocking

**Comment by atilaneves** [comment]
@gnzlbg That'd piss me off too.

**Comment by atilaneves** [comment]
@myrgy With threads, yes, this is fixable. Until then, I don't know of any way to do concurrency in elisp that doesn't involve launching an external process.
