### ISSUE TITLE
How does one use existing compile_commands.json file when not using cmake

### ISSUE THREAD

**Issue by dubnde** [atilaneves/cmake-ide#63]
I am aware this is called `cmake-ide` so probably requires `cmake` projects to work. If one already has an existing `compile_commands.json` file, how can that be plugged into this package? Is it even possible to do this? Or perhaps I need to fake a `cmake` project.

**Comment by atilaneves** [comment]
I just added functionality to do that, actually. Assuming you have the `cmake-ide-build-dir` variable set to the build directory (since that's where it'll look for the compilation database), if you `M-x cmake-ide-load-db` it should set all relevant variables for the current buffer. Add that to the appropriate hook and it should just work. Assuming the DB file is called `compile_commands.json` anyway.

**Comment by dubnde** [comment]
Thanks for the quick response. Yes it is called `compile_commands.json` - I use [bear](https://github.com/rizsotto/Bear) to create it. 

I shall give this a try today once I get to work.

**Comment by dubnde** [comment]
I am seeing the following 

```
cmake-ide [Mon Jun 20 15:29:05 2016]: Converting JSON CDB to IDB
cmake-ide [Mon Jun 20 15:29:06 2016]: Setting flags for file 
File mode specification error: (wrong-type-argument stringp nil)

```
Not exactly sure what `File mode specification error: (wrong-type-argument stringp nil)` means in this case. Let me see if I can make a simple project to get a debug trace.

The code looks like below

```
(defun setup-cmake-ide ()
  (put 'cmake-ide-build-dir 'safe-local-variable 'stringp)

  (defun cmake-ide/hook ()
    (require 'cmake-ide)
    (require 'rtags)
    (require 'irony)

    (cmake-ide-setup)
    (rtags-start-process-unless-running)
    (cmake-ide-load-db)

    ;; Setup the key bindings
    (dolist (mode '(c-mode c++-mode))
      .....)

  (add-hook 'c-mode-hook 'cmake-ide/hook)
  (add-hook 'c++-mode-hook 'cmake-ide/hook))
```

**Comment by atilaneves** [comment]
If you have a sample project, please let me know

**Comment by dubnde** [comment]
I have a simple project at https://github.com/dubnde/cmake-ide-sample

**Comment by atilaneves** [comment]
I pushed a [new commit](https://github.com/atilaneves/cmake-ide/commit/a07cb1429770f168e0aff6b6fc4e8046187f3792) that I tested on your sample project. In order for irony to work, you need to set `cmake-ide-project-dir` as well as `cmake-ide-build-dir`. The problem you're seeing with "End of file" is probably because your cmake-ide-build-dir isn't set to an absolute path

**Comment by dubnde** [comment]
thanks very much. Will give it a try once I can pick up the change from Melpha/elph

**Comment by dubnde** [comment]
Just tried this on a small project with about 30 files and seems to work based on the code below.

  ```
  (use-package cmake-ide)
  (use-package rtags)
  (cmake-ide-setup)

  (setq cmake-ide-build-dir "~/development/testprj/build")
  (setq cmake-ide-project-dir "~/development/testprj")

  (defun cmake-ide/hook ()
    (cmake-ide-load-db))

  (add-hook 'c++-mode-hook #'cmake-ide/hook)

```

My only challenge is to find a way to set the two variables `cmake-ide-build-dir ` and `cmake-ide-project-dir` in the `dir-locals.el` file. I am trying to avoid to hard-code them. However, they don't seem to take effect from the  `dir-locals.el` file even when I hard-code them in there. Need to understand more the evaluation of  `dir-locals.el` settings.

Thanks again for the help. I think this will help me a lot going forward.

**Comment by dubnde** [comment]
I have found a way to not hard-code the `dir` variables - put them in a `c/c++` hook as follows:

```
  (defun cmake-ide/c-c++-hook ()
    (with-eval-after-load 'projectile
      (setq cmake-ide-project-dir (projectile-project-root))
      (setq cmake-ide-build-dir (concat cmake-ide-project-dir "build")))
    (cmake-ide-load-db))

  (add-hook 'c++-mode-hook #'cmake-ide/c-c++-hook)

```

Only issue I need to resolve is why it takes very long to load `*.h` header files. Takes about 10 seconds for `*.c/cpp` source file but about 1 minute for `*.h` header file. Sometimes I have to kill it by pressing `C-g` and then it is instant the next time for the same `*.h` file. My `compile_commands.json` is ~3MB (only)

**Comment by atilaneves** [comment]
header files are problematic - IIRC there's a variable or two to configure how it's done and maybe to turn off the features for headers altogether. 3MB isn't small, BTW!

**Comment by dubnde** [comment]
Sure. Thanks. The following fixed the issue of slow opening of headers. 

```
(setq cmake-ide-header-search-other-file nil
          cmake-ide-header-search-first-including nil
          cmake-ide-try-unique-compiler-flags-for-headers nil)
```

**Comment by dubnde** [comment]
I am curious. Does it run `rc -J` every time a is opened for first time? The file within the same project

**Comment by atilaneves** [comment]
Can I close the issue?

**Comment by dubnde** [comment]
I have closed it. Thanks for the help.
