### ISSUE TITLE
[Request] Add companion to cmake-ide-load-db to load DB only if it has changed

### ISSUE THREAD

**Issue by dubnde** [atilaneves/cmake-ide#64]
Is it possible to add `cmake-ide-may-load-db` only if the DB has changed? Or is this how `cmake-ide-load-db` already works? 

This would allow to hook up the loading of the DB when a c++-mode file is opened but only if the `compile_commands.json` has changed since the last time the file was opened. 

An alternative would be to provide an API to check if the DB has changed and leave the client with the decision to load or not to load the DB.

**Comment by atilaneves** [comment]
It already only bothers reading the compilation DB if it's changed.

**Comment by dubnde** [comment]
ok. thanks. I need to find why it takes so long to load a `C++` file when I add it to the `C++-mode` hook.
