### ISSUE TITLE
Could not find suitable src file for header.h, using all compiler flags

### ISSUE THREAD

**Issue by dubnde** [atilaneves/cmake-ide#65]
I keep on seeing this message. Don't know if it is a warning or not.

`cmake-ide [Mon Jun 27 19:19:27 2016]: Could not find suitable src file for /path/to/header.h, using all compiler flags`

Not exactly sure what it means. It suggests every header file opened tries to look for a similarly named src file. I have the `cmake-ide-header-search-other-file` set to `nil` but not sure if related.

```
               (setq cmake-ide-header-search-other-file nil
                     cmake-ide-header-search-first-including nil
                     cmake-ide-try-unique-compiler-flags-for-headers nil)
```

Should I worry about the message above? Opening files with rtags is not very fast on my 4MB `compile_commands.json `file so I am trying to find as much time as possible,

**Comment by atilaneves** [comment]
Nothing to worry about, it just means it couldn't find a suitable set of flags for that header file so it defaults to using all of them. I could delete the message if it's confusing.

**Comment by dubnde** [comment]
ok. thanks.
