### ISSUE TITLE
No longer available on Melpa?

### ISSUE THREAD

**Issue by astoeckley** [atilaneves/cmake-ide#66]
This is listed on Melpa but when trying to install, it says the package is unavailable.

I tried to simply download and load the cmake-ide.el myself, but then it says the file or directory "levenshtein" is not available.

Can you assist with this installation query? Many thanks!

Also, is rtags necessary for the autocompletion?

**Comment by astoeckley** [comment]
Ok, well my emacs package-install is reporting these as unavailable and won't install them, even as I seem them listed in the packages list for Melpa onscreen, so who knows what is going on.

**Comment by fukuang** [comment]
I'm new to Emacs. But [levenshtein-20141029.816.el](https://melpa.org/packages/levenshtein-20141029.816.el) looks not like a elisp file.

I guess that's the reason when I tried to install `cmake-ide`, Emacs complained about 

    Symbol's value as variable is void: <!DOCTYPE

**Comment by atilaneves** [comment]
`levenshtein` is currently broken. I got around it by downloading the [real version](https://www.emacswiki.org/emacs/levenshtein.el) and recompiling it.

**Comment by CerebrosuS** [comment]
Hey guys,

I also try to get around this issue. But I get 'levenshtein-0' is unavailable. Now I try to install it manually by download it and putting it into ~/.emacs.d/manual_plugins/levenshtein-0.el with the following code in .emacs:
` 
;; plugin path
(add-to-list 'load-path "~/.emacs.d/manual_plugins/")
(load "levenshtein-0.el")
`
But it still doesn't work with installing cmake-ide over MELPA cause the same message still occurs. Any hints maybe?

Greetings

**Comment by atilaneves** [comment]
This was fixed in the meanwhile, maybe the package broke again. I can't reproduce it, sorry.

**Comment by CerebrosuS** [comment]
No Problem,

I will have a look how to come around that problem.

Thx anyway.
Greetings

**Comment by astoeckley** [comment]
Every couple of months I try cmake-ide again, but this problem has never disappeared for me and I've never been able to install it. I don't seem to have enough emacs foo to manually handle the compilation and installation of this dependency myself, despite trying. Maybe a branch that has this package included into the repo fully working would be nice.

**Comment by CerebrosuS** [comment]
Then I am happy tell that it now worked for me. I had to change from stable melpa to the normal melpa system. Then installing levenhstein worked. 

Greetings

**Comment by astoeckley** [comment]
So actually the unstable Melpa proved more stable!

**Comment by CerebrosuS** [comment]
Sounds strange, but give it a try and lt me know whether it works or not.

Greetings

**Comment by astoeckley** [comment]
Well, I was able to install it from regular Melpa finally. But even after emacs restart and setting up with (cmake-ide-setup), I still get an error I've seen before that is also mentioned in 2 other issues:

Symbol’s function definition is void: string-empty-p

So I guess I'll have to give up again on this tool, there seem to be too many moving parts for me to get it working.

**Comment by atilaneves** [comment]
`string-empty-p` was introduced in Emacs 24.4. I assume you're running an older version?

**Comment by astoeckley** [comment]
No, I'm running 24.4.91.1
