### ISSUE TITLE
Flycheck error for .h header files

### ISSUE THREAD

**Issue by zhaojunz** [atilaneves/cmake-ide#69]
Seeing the following error in .h file when it tries to autocomplete (the error seems coming from company-mode):

> Suspicious state from syntax checker c/c++-clang: Checker c/c++-clang returned non-zero exit code 1, but no errors from output: error: invalid argument '-std=c++11' not allowed with 'C/ObjC'

If I change the file to .hh instead of .h, the error goes away, and the behavior is back. 

Thanks for looking into this.

**Comment by atilaneves** [comment]
That means you're using .h for a C++ file. My advice is to not do that. If you must, tell emacs that .h files should be considered to be C++ headers instead of C.
