### ISSUE TITLE
Package metadata not showing in package-list

### ISSUE THREAD

**Issue by PythonNut** [atilaneves/cmake-ide#7]
This probably means that something is wrong with the package headers.

**Comment by omajid** [comment]
http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html says:

> The very first line should have this format:
>
>     ;;; filename --- description

Can you change

    ;;; cmake-ide --- Calls CMake to find out include paths and other compiler flags -*- lexical-binding: t; -*-

to

    ;;; cmake-ide.el --- Calls CMake to find out include paths and other compiler flags -*- lexical-binding: t; -*-

That is, add a `.el` to the file name bit.

**Comment by omajid** [comment]
Thanks for fixing this!

Looks like this issue can be closed now :)
