### ISSUE TITLE
levenshtein-20141029.816.el is incorrect

### ISSUE THREAD

**Issue by fukuang** [atilaneves/cmake-ide#72]
When I tried to install `cmake-ide`, Emacs complained about 

    Symbol's value as variable is void: <!DOCTYPE 

It's caused by [levenshtein-20141029.816.el](https://melpa.org/packages/levenshtein-20141029.816.el), which seems not an elisp file.

**Comment by matt-42** [comment]
Same problem here, it seems related to melpa:
https://melpa.org/packages/levenshtein-20141029.816.el

As a quick fix, you can manually dowload the original source code here:
https://www.emacswiki.org/emacs/levenshtein.el

**Comment by matt-42** [comment]
It has been reported: https://github.com/melpa/melpa/issues/4275

**Comment by rubicus** [comment]
@matt-42 So do you know how to do that? I try to replace the existing levenshtein.el (with HTML) in my elpa folder, but the next time I start emacs it deletes levenshtein and cmake-ide as orphan packages. :(

**Comment by atilaneves** [comment]
@rubicus I just ran into this myself. I downloaded the .el file but then you have to recompile it. Your emacs is loading the byte code from the broken version. Simply run this:

`emacs -batch -f batch-byte-compile elpa/levenshtein-20141029.816/levenshtein.el`

and you should be ok.

**Comment by rubicus** [comment]
Hm, that command didn't seem to do it for me, but running emacs-lisp-byte-compile from inside the file itself did it! Thanks!

**Comment by rubicus** [comment]
This seems to be resolved now. At least it's the right version (20051013.1056) and the download link [here](https://melpa.org/#/levenshtein) seems to contain the right code.
