### ISSUE TITLE
cmake-ide-build-dir without .dir-locals.el? And any advice for debugging?

### ISSUE THREAD

**Issue by FrostedPenguin** [atilaneves/cmake-ide#75]
Literally is there anyway to register current project build directory to cmake-ide-build-dir?

I'm using CMake and I have changed quite a lot of CMake variables related to excutable path or build path. But nothing can change cmake-ide-build-dir. Am I missing something?

Plus, I'm quite new to write C++ codes inside *nix like system with CMake.
However your cmake-ide and other emacs package works really nice so I really satisfied with WRITING codes. But the problem is debugging. 
Whenever I have to debug my code, I have to go to terminal, rerun CMake with debug option, build it again and run gdb with new excutable. 
But this is super annoying. I think there is much better and nicer way to solve this problem. But I can't figure out. 
Most of gdb examples using emacs are based Makefiles which can be integrated with emacs nicely.
So if you don't mind, please let me know the better solution than this.

**Comment by atilaneves** [comment]
`M-;` lets you evaluate elisp in the minibuffer. Set `cmake-ide-build-dir` there to whatever you want (e.g. `(setq cmake-ide-build-dir "/path/to/debug/build")` and start gdb in emacs pointing it to the debug executable. I'd recommend always having two build dirs, one for release builds the other for debug.

**Comment by FrostedPenguin** [comment]
Hmmmm `M-;` seems like inserting a comment. Do you mean `M-:`? This prompts eval in my mini-buffer.
I didn't know this command thanks a lot. 

But my first question was that is there any CMake command to edit cmake-ide-build-dir.

Specifically, cmake-ide read `compile_commands.json` so I thought there is some way to automatically set `cmake-ide-build-dir` with cmake command. 

For example, if I set 'CMAKE_RUNTIME_OUTPUT_DIRECTORY' to my build directory, then `compile_commands.json` would have the path about my build directory .  Then cmake-ide parse it and set the path for me.

**Comment by atilaneves** [comment]
CMake doesn't know about Emacs, so there's no CMake command to do that. `cmake-ide` reads `compile_commands.json`, yes, but to do that it needs to know _where_ to read it from, which is what `cmake-ide-build-dir` does.

**Comment by bel8z** [comment]
Adding on this, I agree on always having one directory for release builds and another for debug ones, but is there a way to run cmake-ide-compile specifying the build mode?

**Comment by atilaneves** [comment]
Not right now, my stance so far is that cmake must be run manually once before `cmake-ide` can work. You'd pass arguments then, including build type. Specifying arguments and running it from emacs the 1st time has been on my TODO list for quite a while.

**Comment by SteveGremory** [comment]
it's 2021
