### ISSUE TITLE
specify files / directories relative to `.dir-locals.el`?

### ISSUE THREAD

**Issue by skebanga** [atilaneves/cmake-ide#77]
I have specified `cmake-ide-cmakelists-dir` and `cmake-ide-build-dir` as relative paths, relative to the location of my `.dir-locals.el` file:

### Project structure:

```
project/
+---- .dir-locals.el
+---- src/
      +---- CMakeLists.txt
      +---- .build/
            +---- debug/
            +---- release/  
```

### `.dir-locals.el`:

```
((nil . (
  (cmake-ide-cmakelists-dir . "src")
  (cmake-ide-build-dir . "src/.build/debug")
)))
```

It seems this doesn't work, and `cmake-ide` requires an absolute path. Is this correct?

### Rationale for relative paths:

- Multiple colleagues use emacs, and as such would like the checked-in version of `.dir-locals.el` to work regardless of where they check out the source tree

- Allowing relative paths means using [`git worktree`](https://git-scm.com/docs/git-worktree) to have multiple branches of the same project checked out in your source tree at the same time will work

How can I specify relative paths in my `.dir-locals.el` please?

**Comment by skebanga** [comment]
It seems as if `cmake-ide-cmakelists-dir` is the culprit here.

If I don't set that variable, then `cmake-ide--locate-cmakelists-impl` will run and find the top-most `CMakeLists.txt`

As such, is there any reason why I would want to have `cmake-ide-cmakelists-dir` set?

What does that give me that `cmake-ide--locate-cmakelists-impl` doesn't?

**Comment by atilaneves** [comment]
The only reason to set `cmake-ide-cmakelists-dir` is to support weird projects (I had one) in which the `CMakeLists.txt` isn't at the top of the directory tree. It shouldn't normally be used.

**Comment by skebanga** [comment]
OK, thanks Atila.

I'll close this.

On a somewhat related topic, what is the `cmake-ide-project-dir` useful for?

Thanks again

**Comment by atilaneves** [comment]
I can't remember what `cmake-ide-project-dir` is for right now :P

**Comment by skebanga** [comment]
Ha, fair enough! 

As far as I can tell (I'm new to emacs/lisp) it's something to do with irony

```
(when (... (featurep 'irony) ...))
  (irony-cdb-json-add-compile-commands-path (cmake-ide--locate-project-dir) ...))
```

No matter, I'll figure it out. 

You project is very well structured and easy to read, so it's really helping me learn lisp, so thanks for that! :)
