### ISSUE TITLE
Include directories not set for flycheck

### ISSUE THREAD

**Issue by vikigenius** [atilaneves/cmake-ide#79]
I have set the cmake-ide project dir and cmake-ide-build-dir, in my dir-locals file.

The compile-commands.json file is in the cmake-ide-build-dir, I however noticed that, the compile commands were using relative paths for includes (Relative to the build directory)
And the project's include dirs were not being set correctly by cmake-ide.

Can someone explain how does setting additional include dirs work, I can't change my compile-commands json file to include absolute paths because it is generated by a complicated build script which uses cmake internally.

**Comment by atilaneves** [comment]
> And the project's include dirs were not being set correctly by cmake-ide.

How were they wrong?

> Can someone explain how does setting additional include dirs work

As a workaround you can always add whatever flags you want to `cmake-ide-flags-c` or `cmake-ide-flags-c++`

**Comment by vikigenius** [comment]
The src-include-dirs were not being set at all.
I debugged and found out that the issue was in the line:

`(file-params (cmake-ide--idb-file-to-obj idb file-name))`

The problem was the file-name is absolute but the idb had relative paths so file-params became nil thereafter.

I tried a temporary fix of converting file-name to relative path and then i could proceed further, but that lead to some other issue i have not been able to isolate.

**Comment by vikigenius** [comment]
Right now i am using a temporary workaround where i check if file-params is nil after:
`(file-params (cmake-ide--idb-file-to-obj idb file-name))`
And if it is i convert the file-name to a relative one and use it, and it seems to be working.:

**Comment by atilaneves** [comment]
If it makes sense, could you create a pull request please? Thanks.

**Comment by vikigenius** [comment]
I just forked your repo and ran your tests:
Somehow five of those tests produced a message:
`Could not find suitable src file for nil, using all compiler flags`
But they still pass

And all of those 5 tests fail after i apply my fix, i am looking into it, but is there something i am missing?
The tests causing problems are:

   test-all-vars
   test-all-vars-ccache
   test-all-vars-ccache-alt
   test-issue-43
   test-issue-52

**Comment by vikigenius** [comment]
Added Pull request : #80

**Comment by atilaneves** [comment]
IIRC those failure messages are fine. Failing UTs, however, are not. But I see the PR is green now. Also, thanks!
