### ISSUE TITLE
cmake-ide--get-existing-definitions always return nil

### ISSUE THREAD

**Issue by erreina** [atilaneves/cmake-ide#8]
The function `cmake-ide--get-existing-definitions` returns the value of the variable `cmake-ide-definitions`  but this is the only place this variable exist, so it will be always `nil`.  It is some kind of legacy code?

**Comment by atilaneves** [comment]
The variable isn't `nil` if set manually by the user. It's meant to be able to set the variable for a project or projects to be included by default. It's the same idea as `cmake-ide-flags-c` and `cmake-ide-flags-c++`.
