### ISSUE TITLE
Add capability to use .rdmrc per project in cmake-ide-maybe-start-rdm

### ISSUE THREAD

**Issue by periklis** [atilaneves/cmake-ide#84]
First of all, since that's my first issue, i would like to thank you for this incredible package. It makes working on CMake projects fun. However, i would like to suggest an enhancement namely a customization point to use a `.rdmrc` per project. Let me elaborate:

Lately i've been working on hobby project with emscripten and stumbled upon making rtags to accept the compiler wrappers `emcc` and `em++`. For example i need a special purpose `.rdmrc` for this project only:
```bash
-C
--compiler-wrappers "emcc;em++"
--isystem /PATH/TO/EMSCRIPTEN/system/include
```

What do think about having a defcustom `cmake-ide-rdm-rc-path` used in `cmake-ide-maybe-start-rdm`, like this:
```emacs-lisp
(defcustom cmake-ide-rdm-rc-path
  "/PATH/TO/PROJECT/ROOT/DIR/.rdmrc"
  "The path to a rdm run control file."
  :group 'cmake-ide
  :type 'string
  :safe #'stringp)

(defun cmake-ide-maybe-start-rdm ()
  "Start the rdm (rtags) server."
  (interactive)
  (when (and (featurep 'rtags)
             (or (file-exists-p (cmake-ide--comp-db-file-name))
                 (cmake-ide--locate-cmakelists)))

    (unless (cmake-ide--process-running-p "rdm")
      (let ((buf (get-buffer-create cmake-ide-rdm-buffer-name)))
        (cmake-ide--message "Starting rdm server")
        (with-current-buffer buf
          (start-process "rdm" (current-buffer)
                         cmake-ide-rdm-executable
                         "-c" cmake-ide-rdm-rc-path))))))
```

**Comment by atilaneves** [comment]
Looks good, please create a PR,

**Comment by periklis** [comment]
Since PR is merged, i'll close this issue.
