### ISSUE TITLE
feature request: query replace across files

### ISSUE THREAD

**Issue by Nidish96** [atilaneves/cmake-ide#87]
There is no direct way for query-replace across the project - It would be very helpful if such a feature could be added.

**Comment by atilaneves** [comment]
What's "query replace"?

**Comment by Nidish96** [comment]
You might sometimes want to rename a particular variable or a function. Doing so can get very painful for even a moderately large project. By query-replace i mean something on the lines of the function in emacs (def kbd M-%) where you can search and replace a string across the current buffer, only, in a project-wide scale.
I remember using something on these lines with ggtags.

**Comment by atilaneves** [comment]
That's functionality provided by rtags

**Comment by dubnde** [comment]
I use `rtags-rename-symbol` for this.
