### ISSUE TITLE
adding files does not write CMakeLists.txt

### ISSUE THREAD

**Issue by rafiks** [atilaneves/cmake-ide#90]
I am trying to learn programming and i have a project dir and a build dir. This is how my setup looks like.

```
(require 'rtags)
(cmake-ide-setup)

(setq cmake-ide-build-dir "/Users/dev/my-sandbox/C/cmake-ide/build/")
(setq cmake-ide-rdm-executable "/usr/local/bin/rdm")
(setq cmake-ide-build-pool-dir "/Users/dev/my-sandbox/C/cmake-ide/build/")
(setq cmake-ide-build-pool-use-persistent-naming t)
(setq cmake-ide-project-dir "/Users/dev/my-sandbox/c/cmake-ide/")
```

Whenever i save a file on the project directory, it looks like it runs rtags but it never appends the buffer-name to the CMakelists.txt.

Am i missing something or is this not how its suppose to work?

Thanks,

**Comment by atilaneves** [comment]
That's only supposed to work if the `CMakeLists.txt` file adds source files by globbing, instead of individually. That's way too much work to implement and I actually don't know why anyone would want to manually list source files.

**Comment by ideasman42** [comment]
Globing files is problematic if you use git-bisect or work with others, see: https://stackoverflow.com/a/18538444/432509

Think this should be closed, if you manually list source files, manually adding to `CMakeLists.txt` is expected.

**Comment by atilaneves** [comment]
I disagree with globbing being problematic - I think it's crazy to add files manually.  But yes, this should be closed.

**Comment by ideasman42** [comment]
Globbing is fine as long as everyone remembers to manually re-run cmake when files are added/removed. (when bisecting, switching branches - etc)
