### ISSUE TITLE
Feature request: ability to disable flycheck

### ISSUE THREAD

**Issue by ideasman42** [atilaneves/cmake-ide#94]
Flycheck with GCC spesific flags isn't usable with clang (prints many errors about unknown options).

So I ended up disabling flycheck. Now on opening a file I get the error:

    Error running timer ‘flycheck-buffer’: (user-error "Flycheck mode disabled")

It would be useful if there were a way to tell `cmake-ide` not to call flycheck.

**Comment by atilaneves** [comment]
IMHO it'd be far better to provide an easy way to filter the flycheck clang flags instead. You can do this manually right now with `(setq flycheck-clang-args '(...))`

**Comment by ideasman42** [comment]
Agree that filtering flags would be useful, but think its not so unreasonable to be able to disable flycheck too.

**Comment by atilaneves** [comment]
Well, flycheck doesn't run if it isn't installed - and disabling it means disabling a good part of the reason cmake-ide exists in the first place.

In any case, flycheck [can disable syntax checkers](http://www.flycheck.org/en/latest/user/syntax-checkers.html) - I think this is what you want.

**Comment by ideasman42** [comment]
Ah, I must have installed it when first setting up cmake-ide,

I've since removed, although it would be nice to be able to use for other languages, but not C/C++, I think this isn't so important.
