### ISSUE TITLE
Unable to use another window for compiler output

### ISSUE THREAD

**Issue by ideasman42** [atilaneves/cmake-ide#96]
When building, a split view is opened for the output.

It's possible to close this window, open a new window and set the buffer to the build output.

However when building again, the other window isn't used.
Instead a new split is created in the same window the source code is in.

----

It would be useful if any existing compiler output windows would be re-used instead of creating new splits.

**Comment by atilaneves** [comment]
I'm pretty sure that's configureable but that's just compiling with emacs, I don't think there's anything `cmake-ide` specific.

**Comment by ideasman42** [comment]
Okay, seems this is out of scope for cmake-ide, thanks for the reply.

Asked this question [here](http://emacs.stackexchange.com/questions/31761).

**Comment by ideasman42** [comment]
If anyone stumbles on this issue, see solution here: https://emacs.stackexchange.com/questions/21389
